CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');
CREATE TABLE public.profiles (id uuid PRIMARY KEY, display_name text NOT NULL DEFAULT '' CHECK (char_length(display_name) <= 100), headline text NOT NULL DEFAULT '' CHECK (char_length(headline) <= 160), banned boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_profile_read ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY own_profile_insert ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid() AND NOT banned);
CREATE POLICY own_profile_update ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid() AND NOT banned) WITH CHECK (id = auth.uid() AND NOT banned);
REVOKE UPDATE ON public.profiles FROM authenticated;
GRANT UPDATE (display_name, headline) ON public.profiles TO authenticated;
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL, UNIQUE(user_id, role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_role_read ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role); $$;
CREATE FUNCTION public.account_allowed() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT auth.uid() IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.profiles WHERE id = auth.uid() AND banned); $$;
CREATE TABLE public.companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL CHECK(char_length(name) BETWEEN 1 AND 100), slug text UNIQUE NOT NULL CHECK(slug ~ '^[a-z0-9-]+$'), website text NOT NULL DEFAULT '', industry text NOT NULL DEFAULT '', location text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')), featured boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.companies TO anon, authenticated;
GRANT ALL ON public.companies TO service_role;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
CREATE POLICY public_approved_companies ON public.companies FOR SELECT TO anon, authenticated USING (status = 'approved');
CREATE TABLE public.company_affiliations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, company_id uuid NOT NULL REFERENCES public.companies(id), function text NOT NULL, level text NOT NULL CHECK(level IN ('Junior','Senior','Leadership')), email_hmac text NOT NULL, verified_at timestamptz, discoverable boolean NOT NULL DEFAULT false, UNIQUE(user_id,company_id));
GRANT SELECT ON public.company_affiliations TO authenticated;
GRANT ALL ON public.company_affiliations TO service_role;
ALTER TABLE public.company_affiliations ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_affiliations ON public.company_affiliations FOR SELECT TO authenticated USING(user_id = auth.uid() AND public.account_allowed());
CREATE TABLE public.company_submissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, company_name text NOT NULL CHECK(char_length(company_name) BETWEEN 2 AND 100), website text NOT NULL CHECK(char_length(website) BETWEEN 4 AND 255), function text NOT NULL CHECK(char_length(function) BETWEEN 1 AND 60), status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT ON public.company_submissions TO authenticated;
GRANT ALL ON public.company_submissions TO service_role;
ALTER TABLE public.company_submissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_submissions_read ON public.company_submissions FOR SELECT TO authenticated USING(user_id = auth.uid() AND public.account_allowed());
CREATE POLICY own_submissions_insert ON public.company_submissions FOR INSERT TO authenticated WITH CHECK(user_id = auth.uid() AND status = 'pending' AND public.account_allowed());
CREATE FUNCTION public.limit_company_submissions() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN PERFORM pg_advisory_xact_lock(hashtextextended(NEW.user_id::text, 11)); IF (SELECT count(*) FROM public.company_submissions WHERE user_id = NEW.user_id AND created_at > now() - interval '24 hours') >= 3 THEN RAISE EXCEPTION 'You can submit up to 3 companies per day.'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER company_submission_limit BEFORE INSERT ON public.company_submissions FOR EACH ROW EXECUTE FUNCTION public.limit_company_submissions();
CREATE TABLE public.referral_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), seeker_id uuid NOT NULL, referrer_id uuid, company_id uuid NOT NULL REFERENCES public.companies(id), job_url text NOT NULL CHECK(char_length(job_url) <= 1000), note text NOT NULL CHECK(char_length(note) <= 2000), status text NOT NULL DEFAULT 'REQUESTED' CHECK(status IN ('REQUESTED','ACCEPTED','CLAIMED','DECLINED','EXPIRED','WITHDRAWN','REFERRED','INTERVIEWING','OFFER','HIRED','REJECTED','CLOSED')), created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'));
GRANT SELECT ON public.referral_requests TO authenticated;
GRANT ALL ON public.referral_requests TO service_role;
ALTER TABLE public.referral_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY request_participant_read ON public.referral_requests FOR SELECT TO authenticated USING(public.account_allowed() AND (seeker_id = auth.uid() OR referrer_id = auth.uid()));
CREATE TABLE public.messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), request_id uuid NOT NULL REFERENCES public.referral_requests(id), sender_id uuid NOT NULL, body text NOT NULL CHECK(char_length(body) BETWEEN 1 AND 2000), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.messages TO authenticated;
GRANT ALL ON public.messages TO service_role;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY message_participant_read ON public.messages FOR SELECT TO authenticated USING(public.account_allowed() AND EXISTS(SELECT 1 FROM public.referral_requests r WHERE r.id = request_id AND r.status IN ('ACCEPTED','CLAIMED','REFERRED','INTERVIEWING','OFFER','HIRED','REJECTED','CLOSED') AND (r.seeker_id = auth.uid() OR r.referrer_id = auth.uid())));
CREATE FUNCTION public.explore_companies() RETURNS TABLE(id uuid, name text, slug text, website text, industry text, location text, verified_count bigint, functions text[], levels text[], joining boolean) LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT c.id,c.name,c.slug,c.website,c.industry,c.location, count(a.id) FILTER(WHERE a.verified_at IS NOT NULL AND a.discoverable AND NOT EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = a.user_id AND p.banned)), coalesce(array_agg(DISTINCT a.function) FILTER(WHERE a.verified_at IS NOT NULL AND a.discoverable AND NOT EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = a.user_id AND p.banned)), ARRAY[]::text[]), coalesce(array_agg(DISTINCT a.level) FILTER(WHERE a.verified_at IS NOT NULL AND a.discoverable AND NOT EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = a.user_id AND p.banned)), ARRAY[]::text[]), NOT EXISTS(SELECT 1 FROM public.company_affiliations v WHERE v.company_id = c.id AND v.verified_at IS NOT NULL AND v.discoverable AND NOT EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = v.user_id AND p.banned)) FROM public.companies c LEFT JOIN public.company_affiliations a ON a.company_id = c.id WHERE c.status = 'approved' GROUP BY c.id HAVING count(a.id) FILTER(WHERE a.verified_at IS NOT NULL AND a.discoverable AND NOT EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = a.user_id AND p.banned)) > 0 OR c.featured OR count(a.id) > 0; $$;
REVOKE ALL ON FUNCTION public.explore_companies() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.explore_companies() TO anon, authenticated;
CREATE INDEX affiliations_company_idx ON public.company_affiliations(company_id);
CREATE INDEX requests_seeker_idx ON public.referral_requests(seeker_id,created_at);
CREATE INDEX requests_referrer_idx ON public.referral_requests(referrer_id,created_at);
CREATE INDEX messages_request_idx ON public.messages(request_id,created_at);
CREATE INDEX submissions_user_idx ON public.company_submissions(user_id,created_at);