import {useEffect,useState} from "react";
type Status={enabled?:boolean;active?:boolean;role?:string;csrf?:string};
export default function AdminSmoke(){
 const[status,setStatus]=useState<Status>({}),[data,setData]=useState<unknown>(),[error,setError]=useState("");
 const load=async()=>{const r=await fetch("/api/admin/smoke/status",{credentials:"include"});if(r.status===404){setStatus({});return}const s=await r.json();setStatus(s);if(s.active){const f=await fetch("/api/admin/smoke/snapshot",{credentials:"include"});if(f.ok)setData(await f.json())}};
 useEffect(()=>{const meta=document.createElement("meta");meta.name="robots";meta.content="noindex,nofollow,noarchive";document.head.appendChild(meta);void load();return()=>meta.remove()},[]);
 const post=async(path:string,body:object={})=>{setError("");const response=await fetch(`/api/admin/smoke/${path}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","x-csrf-token":status.csrf||""},body:JSON.stringify({...body,csrf:status.csrf})});if(!response.ok){const payload=await response.json().catch(()=>({}));setError(payload.error||`Smoke action failed (${response.status})`);return}await load()};
 if(!status.enabled)return <main className="p-8"><h1>Not found</h1></main>;
 return <main className="min-h-screen bg-slate-50"><div className="sticky top-0 z-50 bg-amber-300 px-4 py-3 text-center text-sm font-black tracking-widest text-black">SMOKE TEST · SYNTHETIC DATA</div><section className="mx-auto max-w-2xl p-6"><h1 className="text-3xl font-bold">Protected smoke fixture</h1><p className="mt-2 text-slate-600">Isolated synthetic state. No live users, messages, payments or files.</p>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{status.active?<><pre className="mt-6 overflow-auto rounded-xl bg-slate-900 p-4 text-xs text-white">{JSON.stringify(data,null,2)}</pre><div className="mt-4 flex gap-3"><button onClick={()=>post("reset")} className="rounded-lg border px-4 py-2">Reset</button><button onClick={()=>post("exit")} className="rounded-lg bg-slate-900 px-4 py-2 text-white">Exit</button></div></>:<div className="mt-6 grid grid-cols-2 gap-3">{["seeker","referrer","admin","employer"].map(role=><button key={role} onClick={()=>post("activate",{role})} className="rounded-xl border bg-white p-4 capitalize">Enter as {role}</button>)}</div>}</section></main>;
}
