import { ArrowRight, Menu } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { Brand } from "@/components/Brand";
import { SignInButton } from "@/_core/auth";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";

export default function Home() {
  const [, go] = useLocation();
  const [acceptedReferrals, setAcceptedReferrals] = useState<number | null>(null);
  useEffect(() => {
    let active = true;
    void fetch("/api/referral-impact").then(response => response.json()).then(payload => {
      if (active && typeof payload.acceptedReferrals === "number" && payload.acceptedReferrals > 0) setAcceptedReferrals(Math.floor(payload.acceptedReferrals));
    }).catch(() => undefined);
    return () => { active = false; };
  }, []);
  return   <main className="min-h-dvh bg-[#F5F4EF] text-[#191713]">
    <header className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5 sm:px-8 lg:px-0"><Brand /><nav aria-label="Public navigation" className="hidden items-center gap-7 sm:flex"><Link href="/privacy" className="text-sm font-semibold text-slate-600 hover:text-slate-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#0B57D0]">Privacy</Link><Link href="/support" className="text-sm font-semibold text-slate-600 hover:text-slate-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#0B57D0]">How it works</Link><SignInButton><button className="min-h-11 rounded-xl border border-slate-200 bg-white px-5 text-sm font-semibold text-[#0B57D0] hover:border-blue-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0B57D0]">Sign in</button></SignInButton></nav><div className="sm:hidden"><Sheet><SheetTrigger asChild><button aria-label="Open navigation menu" className="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white text-slate-700"><Menu className="h-5 w-5" /></button></SheetTrigger><SheetContent side="right" className="w-[min(84vw,20rem)] bg-white p-0"><SheetHeader className="border-b border-slate-100 px-5 py-5"><SheetTitle className="text-left">Menu</SheetTitle><SheetDescription className="sr-only">Public navigation</SheetDescription></SheetHeader><nav className="flex flex-col gap-1 p-3"><SheetClose asChild><Link href="/support" className="min-h-12 rounded-lg px-4 py-3 text-sm font-semibold">How it works</Link></SheetClose><SheetClose asChild><Link href="/privacy" className="min-h-12 rounded-lg px-4 py-3 text-sm font-semibold">Privacy</Link></SheetClose><SignInButton><button className="mt-2 min-h-12 w-full rounded-lg bg-[#0B57D0] px-4 text-left text-sm font-semibold text-white">Sign in</button></SignInButton></nav></SheetContent></Sheet></div></header>
    <section className="mx-auto grid max-w-6xl gap-10 px-5 pb-12 pt-7 sm:px-8 sm:pb-20 sm:pt-14 lg:grid-cols-[1.1fr_.9fr] lg:gap-16 lg:px-0">
      <div><h1 className="max-w-2xl text-[2.35rem] font-semibold leading-[1.02] tracking-[-.055em] sm:text-[3.65rem]">A referral should<br/>open a door.<br/><span className="text-[#0B57D0]">Not waste your time.</span></h1><p className="mt-5 max-w-lg text-base leading-7 text-slate-600">Paste a job. We prepare the ask and match it privately to verified employees who can choose how to help.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">
        <button onClick={() => go("/start")} className="group min-h-40 rounded-[20px] bg-[#0B57D0] p-6 text-left text-white transition duration-150 hover:bg-[#0847AD] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#0B57D0] motion-reduce:transition-none"><span className="text-[11px] font-bold uppercase tracking-[.2em] text-blue-100">For job seekers</span><span className="mt-4 flex items-center justify-between text-lg font-semibold">I need a referral <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1 motion-reduce:transition-none" /></span><span className="mt-2 block text-sm leading-6 text-blue-100">Share the role. Add your resume.</span></button>
        <button onClick={() => go("/referrer")} className="group min-h-40 rounded-[20px] border border-slate-200 bg-white p-6 text-left transition duration-150 hover:border-blue-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#0B57D0] motion-reduce:transition-none"><span className="text-[11px] font-bold uppercase tracking-[.2em] text-[#0B57D0]">For employees</span><span className="mt-4 flex items-center justify-between text-lg font-semibold">I can refer someone <ArrowRight className="h-5 w-5 text-[#0B57D0] transition-transform group-hover:translate-x-1 motion-reduce:transition-none" /></span><span className="mt-2 block text-sm leading-6 text-slate-600">Review a complete, private request.</span></button>
      </div>{acceptedReferrals ? <p className="mt-6 text-sm font-semibold text-emerald-700">{acceptedReferrals} referrals accepted</p> : null}<p className="mt-4 text-sm text-slate-500">No public request feed. Nothing is shared without a choice.</p></div>
      <aside className="rounded-[22px] border border-slate-200 bg-white p-7 sm:p-8"><h2 className="text-2xl font-semibold leading-tight tracking-[-.035em]">Built for a careful yes.<br/>And an easy no.</h2><ol className="mt-7 space-y-6"><Step n="01" title="Paste once" body="We identify the role and company."/><Step n="02" title="Review with context" body="Resume, role and a forwardable note."/><Step n="03" title="You stay in control" body="Nothing is shared without a choice."/></ol><div className="mt-8 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-900"><strong>Private by default</strong><span className="mt-1 block text-emerald-800">Verified company access.</span></div></aside>
    </section><footer className="mx-auto max-w-6xl border-t border-slate-200 px-5 py-6 text-sm text-slate-600 sm:px-8 lg:px-0"><Link href="/employer" className="font-semibold text-[#0B57D0] hover:underline">Hiring for your company?</Link></footer>
  </main>;
}
function Step({n,title,body}:{n:string;title:string;body:string}){return <li className="flex gap-4"><span className="text-xs font-bold text-[#0B57D0]">{n}</span><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-sm leading-6 text-slate-600">{body}</p></div></li>}
