import { Bell, CheckCheck, CircleDotDashed, MessageCircle, Sparkles } from "lucide-react";
import { useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { notifications as demoNotifications } from "@/lib/demoData";
import { trpc } from "@/lib/trpc";

export default function Notifications() {
  const { data: liveNotifications } = trpc.notifications.list.useQuery(); const utils = trpc.useUtils();
  const [previewNotifications, setPreviewNotifications] = useState(demoNotifications);
  const persisted = liveNotifications?.map(item => ({ id: item.id, title: item.title, body: item.body, time: item.createdAt ? new Date(item.createdAt).toLocaleDateString() : "Recently", type: item.category === "referral" ? "Referral Request" : item.category === "message" ? "Message" : item.category === "status" ? "Status" : "Opportunity", unread: !item.readAt }));
  const notifications = persisted?.length ? persisted : previewNotifications; const isPersisted = Boolean(persisted?.length); const unread = notifications.filter(item => item.unread).length;
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => utils.notifications.list.invalidate() });
  const markAll = () => { if (isPersisted) { notifications.filter(item => item.unread).forEach(item => markRead.mutate({ notificationId: item.id })); return; } setPreviewNotifications(list => list.map(item => ({ ...item, unread: false }))); };
  const clickNotification = (id: number) => { if (isPersisted) { markRead.mutate({ notificationId: id }); return; } setPreviewNotifications(list => list.map(item => item.id === id ? { ...item, unread: false } : item)); };
  const icons = { "Referral Request": Bell, Message: MessageCircle, Status: CircleDotDashed, Opportunity: Sparkles };
  return <DashboardLayout title="Notifications" eyebrow="Stay in the loop" actions={<button onClick={markAll} disabled={unread === 0 || markRead.isPending} className="hidden items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 disabled:opacity-40 sm:inline-flex"><CheckCheck className="h-4 w-4" />Mark all as read</button>}><div className="mx-auto max-w-3xl"><div className="flex items-end justify-between"><div><h2 className="text-lg font-semibold tracking-[-0.04em]">What’s new</h2><p className="mt-1 text-sm text-slate-500">{unread ? `${unread} updates need your attention.` : "You’re all caught up."}</p></div><button onClick={markAll} className="text-xs font-bold text-violet-700 sm:hidden">Mark all read</button></div><div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_14px_34px_rgba(28,25,55,0.045)]">{notifications.map(item => { const Icon = icons[item.type as keyof typeof icons]; return <button key={item.id} onClick={() => clickNotification(item.id)} className={`flex w-full gap-4 border-b border-slate-100 p-5 text-left last:border-b-0 transition hover:bg-[#FBFBFE] ${item.unread ? "bg-violet-50/50" : ""}`}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-700"><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-3"><span className="font-semibold text-slate-950">{item.title}</span><span className="shrink-0 text-[11px] text-slate-400">{item.time}</span></span><span className="mt-1.5 block text-sm leading-6 text-slate-600">{item.body}</span><span className="mt-2 block text-[10px] font-bold uppercase tracking-[0.12em] text-violet-600">{item.type}</span></span>{item.unread && <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-violet-600" />}</button>})}</div></div></DashboardLayout>;
}
