import { ArrowLeft, Check, CreditCard, ShieldCheck } from "lucide-react";
import React, { useState } from "react";
import { Link } from "wouter";
import { Brand } from "@/components/Brand";
import { addPurchasedTokens, getJobSeekerTokens, setJobSeekerTokens, tokenReturnPath, type TokenRole } from "@/lib/tokens";

export default function Premium() {
  const role: TokenRole = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("role") === "referrer" ? "referrer" : "job_seeker";
  const referrer = role === "referrer";
  const storageKey = referrer ? "bridge-referrer-paid-tokens" : "bridge-tokens";
  const label = referrer ? "referral action" : "direct application";
  const [count, setCount] = useState(1);
  const [paid, setPaid] = useState(false);
  const balance = referrer ? Number(localStorage.getItem(storageKey) || 0) : getJobSeekerTokens();
  const finish = () => { const next = addPurchasedTokens(referrer ? Number(localStorage.getItem(storageKey) || 0) : getJobSeekerTokens(), count); if (referrer) localStorage.setItem(storageKey, String(next)); else setJobSeekerTokens(next); setPaid(true); };
  const returnPath = tokenReturnPath(role);

  if (paid) return <main data-skipwait-screen="premium" className="min-h-screen bg-slate-50 px-6 py-6 text-slate-950"><div className="mx-auto max-w-xl"><Brand /><section className="mt-20 rounded-2xl border border-slate-200 bg-white p-9 text-center shadow-sm"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Check className="h-6 w-6" /></span><h1 className="mt-5 text-3xl font-semibold">{count} purchased token{count > 1 ? "s" : ""} added.</h1><p className="mt-3 text-sm leading-6 text-slate-600">Simulation complete. {referrer ? "Your Referrer wallet will show these separately from your free allowance." : "Your Application Tokens balance now includes your purchased tokens."}</p><Link href={returnPath} className="mt-8 inline-flex rounded-lg bg-[#0B57D0] px-5 py-3 text-sm font-semibold text-white hover:bg-[#0847AD]">Continue</Link></section></div></main>;

  return <main data-skipwait-screen="premium" className="min-h-screen bg-slate-50 px-6 py-6 text-slate-950"><div className="mx-auto max-w-3xl"><Brand /><Link href={returnPath} className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft className="h-4 w-4" />Back</Link><section className="mt-10 grid gap-8 rounded-2xl border border-slate-200 bg-white p-8 shadow-sm lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0B57D0]">More {referrer ? "Referrer" : "application"} tokens</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.055em]">Simple: $1 per token.</h1><p className="mt-4 text-base leading-7 text-slate-600">You have <strong>{balance} {referrer ? "purchased" : "included"} token{balance === 1 ? "" : "s"}</strong> available. Your first 3 {label}s are included; add only what you need after that.</p><div className="mt-8 flex items-center gap-4"><button onClick={() => setCount(Math.max(1, count - 1))} className="grid h-11 w-11 place-items-center rounded-full border border-slate-200 text-lg hover:bg-slate-50">−</button><div className="min-w-24 text-center"><p className="text-3xl font-semibold">{count}</p><p className="text-xs text-slate-500">tokens</p></div><button onClick={() => setCount(count + 1)} className="grid h-11 w-11 place-items-center rounded-full border border-slate-200 text-lg hover:bg-slate-50">+</button></div></div><aside className="rounded-xl bg-slate-900 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-200">Checkout summary</p><div className="mt-6 flex justify-between text-sm"><span>{count} {label} token{count > 1 ? "s" : ""}</span><strong>${count}</strong></div><button onClick={finish} className="mt-7 flex w-full items-center justify-center gap-2 rounded-lg bg-[#0B57D0] px-4 py-3 text-sm font-semibold hover:bg-[#0847AD]"><CreditCard className="h-4 w-4" />Simulate ${count} purchase</button><div className="mt-5 flex gap-2 text-xs leading-5 text-slate-400"><ShieldCheck className="h-4 w-4 shrink-0 text-emerald-500" />Design simulation only. No payment is processed.</div></aside></section></div></main>;
}
