import { useEffect, useState } from "react";
import { Link } from "wouter";
import { useAuth } from "@/_core/auth";
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Inbox, RefreshCw, ShieldCheck, Sparkles, Wallet } from "lucide-react";
import { AccountMenu } from "@/components/AccountMenu";
import { Brand } from "@/components/Brand";
import { SignInButton } from "@/_core/auth";
import { readApiJson } from "@/lib/apiResponse";

type ReferrerImpactSummary = { acceptedReferrals: number; pendingRequests: number; declinedRequests: number; unreadMessages: number; creditsRemaining: number; recentAccepted: Array<{ id: number; companyDomain: string; acceptedAt: string }> };
type CompanyAccess = { verifiedCompanyAccess: boolean; workEmailDomain: string | null; error?: string };

function relativeDays(iso: string) {
  const days = Math.floor((Date.now() - new Date(iso).getTime()) / 86_400_000);
  if (!Number.isFinite(days) || days < 0) return "";
  if (days === 0) return "today";
  if (days === 1) return "yesterday";
  return `${days} days ago`;
}

function ImpactStat({ label, value, detail, icon: Icon, accent, valueClass }: { label: string; value: number; detail: string; icon: typeof Inbox; accent: string; valueClass?: string }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className={`mt-2 text-3xl font-semibold tracking-[-0.05em] ${valueClass || "text-slate-950"}`}>{value}</p><p className="mt-2 text-xs font-medium text-slate-500">{detail}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${accent}`}><Icon className="h-5 w-5" /></span></div></div>;
}

export default function ReferrerImpact() {
  const { isLoaded, isSignedIn, getToken } = useAuth();
  const [summary, setSummary] = useState<ReferrerImpactSummary | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [companyAccess, setCompanyAccess] = useState<CompanyAccess | null>(null);
  const [accessReady, setAccessReady] = useState(!isSignedIn);
  const [accessError, setAccessError] = useState("");
  const hasVerifiedWorkEmail = Boolean(companyAccess?.verifiedCompanyAccess && companyAccess.workEmailDomain);
  const loadCompanyAccess = async () => { if (!isSignedIn) { setCompanyAccess(null); setAccessReady(true); return; } setAccessError(""); try { const token = await getToken(); const response = await fetch("/api/company-referrals/access", { credentials: "include", headers: token ? { Authorization: `Bearer ${token}` } : {} }); const payload = await readApiJson<CompanyAccess>(response, "We could not check your work-email access"); if (!response.ok) throw new Error("We could not check your work-email access"); setCompanyAccess({ verifiedCompanyAccess: Boolean(payload.verifiedCompanyAccess), workEmailDomain: payload.workEmailDomain ?? null }); } catch (reason) { setAccessError(reason instanceof Error ? reason.message : "We could not check your work-email access"); } finally { setAccessReady(true); } };
  const loadSummary = async () => {
    if (!isSignedIn) return;
    setLoading(true); setError("");
    try {
      const token = await getToken();
      const response = await fetch("/api/referrer/impact-summary", { credentials: "include", headers: token ? { Authorization: `Bearer ${token}` } : {} });
      const payload = await readApiJson<ReferrerImpactSummary & { error?: string }>(response, "We could not load your referral impact");
      if (!response.ok) throw new Error(payload.error || "We could not load your referral impact");
      setSummary({ acceptedReferrals: Math.max(0, Number(payload.acceptedReferrals) || 0), pendingRequests: Math.max(0, Number(payload.pendingRequests) || 0), declinedRequests: Math.max(0, Number(payload.declinedRequests) || 0), unreadMessages: Math.max(0, Number(payload.unreadMessages) || 0), creditsRemaining: Math.max(0, Number(payload.creditsRemaining) || 0), recentAccepted: Array.isArray(payload.recentAccepted) ? payload.recentAccepted.slice(0, 5) : [] });
    } catch (reason) { setSummary(null); setError(reason instanceof Error ? reason.message : "We could not load your referral impact"); }
    finally { setLoading(false); }
  };
  useEffect(() => { void loadCompanyAccess(); }, [isSignedIn]);
  useEffect(() => { if (isSignedIn && hasVerifiedWorkEmail) void loadSummary(); }, [isSignedIn, hasVerifiedWorkEmail]);
  if (!isLoaded) return <main data-skipwait-screen="referrer-impact-loading" className="h-dvh min-h-dvh overflow-hidden bg-slate-50 px-5 py-4 text-slate-950"><div className="mx-auto flex h-full max-w-xl flex-col"><header className="flex h-10 shrink-0 items-center justify-between"><Brand /><div className="h-9 w-9 animate-pulse rounded-full bg-slate-200" /></header><section className="flex min-h-0 flex-1 items-center"><div className="w-full animate-pulse rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="h-3 w-28 rounded bg-blue-100" /><div className="mt-5 h-9 w-3/4 rounded bg-slate-100" /><div className="mt-3 h-4 w-full rounded bg-slate-100" /><div className="mt-7 h-12 w-full rounded-lg bg-blue-100" /></div></section></div></main>;

  if (!isSignedIn) return <main data-skipwait-screen="referrer-impact-sign-in" className="h-dvh min-h-dvh overflow-hidden bg-slate-50 px-5 py-4 text-slate-950"><div className="mx-auto flex h-full max-w-xl flex-col"><header className="flex h-10 shrink-0 items-center justify-between"><Brand /><AccountMenu /></header><section className="flex min-h-0 flex-1 flex-col items-center justify-center text-center"><span aria-hidden="true" className="grid h-14 w-14 place-items-center rounded-3xl bg-blue-50 text-[#0B57D0]"><Sparkles className="h-6 w-6" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-[#0B57D0]">Referral impact</p><h1 className="mt-3 text-[1.85rem] font-semibold leading-[1.04] tracking-[-.045em]">Sign in with your work email to see your referral impact</h1><p className="mt-3 text-sm leading-6 text-slate-600">Accepted referrals, pending decisions, and private messages — all in one private view.</p><SignInButton><button type="button" className="mt-6 rounded-lg bg-[#0B57D0] px-5 py-3 text-sm font-semibold text-white">Secure sign in</button></SignInButton></section></div></main>;

  if (!accessReady) return <main data-skipwait-screen="referrer-impact-loading" className="h-dvh min-h-dvh overflow-hidden bg-slate-50 px-5 py-4 text-slate-950"><div className="mx-auto flex h-full max-w-xl flex-col"><header className="flex h-10 shrink-0 items-center justify-between"><Brand /><AccountMenu /></header><section className="flex min-h-0 flex-1 items-center"><div className="w-full animate-pulse rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="h-3 w-28 rounded bg-blue-100" /><div className="mt-5 h-9 w-3/4 rounded bg-slate-100" /><div className="mt-3 h-4 w-full rounded bg-slate-100" /><div className="mt-7 grid grid-cols-2 gap-3"><div className="h-28 rounded-xl bg-slate-100" /><div className="h-28 rounded-xl bg-slate-100" /><div className="h-28 rounded-xl bg-slate-100" /><div className="h-28 rounded-xl bg-slate-100" /></div></div></section></div></main>;

  if (accessError) return <main data-skipwait-screen="referrer-impact-access-error" className="h-dvh min-h-dvh overflow-hidden bg-slate-50 px-5 py-4 text-slate-950"><div className="mx-auto flex h-full max-w-xl flex-col"><header className="flex h-10 shrink-0 items-center justify-between"><Brand /><AccountMenu /></header><section className="flex min-h-0 flex-1 flex-col justify-center"><div role="alert" className="rounded-2xl border border-rose-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-rose-700">Something went wrong</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.03em]">We could not check your work-email access.</h1><p className="mt-3 text-sm leading-6 text-slate-600">{accessError}</p><button type="button" onClick={() => { void loadCompanyAccess(); }} className="mt-6 inline-flex items-center justify-center gap-2 rounded-lg bg-[#0B57D0] px-5 py-3 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4" />Try again</button></div></section></div></main>;

  if (!hasVerifiedWorkEmail) return <main data-skipwait-screen="referrer-impact-setup" className="h-dvh min-h-dvh overflow-hidden bg-slate-50 px-5 py-4 text-slate-950"><div className="mx-auto flex h-full max-w-xl flex-col"><header className="flex h-10 shrink-0 items-center justify-between"><Brand /><AccountMenu /></header><Link href="/inbox" className="mt-5 inline-flex w-fit items-center gap-1 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4" />Back to inbox</Link><section className="flex min-h-0 flex-1 flex-col items-center justify-center text-center"><span aria-hidden="true" className="grid h-14 w-14 place-items-center rounded-3xl bg-blue-50 text-[#0B57D0]"><ShieldCheck className="h-6 w-6" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-[#0B57D0]">Referral impact</p><h1 className="mt-3 text-[1.85rem] font-semibold leading-[1.04] tracking-[-.045em]">Verify your work email</h1><p className="mt-3 text-sm leading-6 text-slate-600">Confirm a company email with a one-time code to unlock your private referral impact.</p><Link href="/referrer?setup=work-email" className="mt-6 inline-flex items-center justify-center gap-2 rounded-lg bg-[#0B57D0] px-5 py-3 text-sm font-semibold text-white">Add work email <ArrowRight className="h-4 w-4" /></Link></section></div></main>;

  if (loading && !summary && !error) return <main data-skipwait-screen="referrer-impact-loading" className="h-dvh min-h-dvh overflow-hidden bg-slate-50 px-5 py-4 text-slate-950"><div className="mx-auto flex h-full max-w-xl flex-col"><header className="flex h-10 shrink-0 items-center justify-between"><Brand /><AccountMenu /></header><section className="flex min-h-0 flex-1 items-center"><div className="w-full animate-pulse rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="h-3 w-28 rounded bg-blue-100" /><div className="mt-5 h-9 w-3/4 rounded bg-slate-100" /><div className="mt-3 h-4 w-full rounded bg-slate-100" /><div className="mt-7 grid grid-cols-2 gap-3"><div className="h-28 rounded-xl bg-slate-100" /><div className="h-28 rounded-xl bg-slate-100" /><div className="h-28 rounded-xl bg-slate-100" /><div className="h-28 rounded-xl bg-slate-100" /></div></div></section></div></main>;

  if (error) return <main data-skipwait-screen="referrer-impact-error" className="h-dvh min-h-dvh overflow-hidden bg-slate-50 px-5 py-4 text-slate-950"><div className="mx-auto flex h-full max-w-xl flex-col"><header className="flex h-10 shrink-0 items-center justify-between"><Brand /><AccountMenu /></header><section className="flex min-h-0 flex-1 flex-col justify-center"><div role="alert" className="rounded-2xl border border-rose-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-rose-700">Something went wrong</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.03em]">We could not load your referral impact.</h1><p className="mt-3 text-sm leading-6 text-slate-600">{error}</p><button type="button" onClick={() => { void loadSummary(); }} className="mt-6 inline-flex items-center justify-center gap-2 rounded-lg bg-[#0B57D0] px-5 py-3 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4" />Try again</button></div></section></div></main>;

  if (!summary) return null;
  const hasAccepted = summary.acceptedReferrals > 0;
  return <main data-skipwait-screen="referrer-impact" className="min-h-dvh bg-slate-50 px-5 py-4 text-slate-950"><div className="mx-auto flex min-h-[calc(100dvh-2rem)] max-w-xl flex-col"><header className="flex h-10 shrink-0 items-center justify-between"><Brand /><AccountMenu /></header><Link href="/inbox" className="mt-5 inline-flex w-fit items-center gap-1 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4" />Back to inbox</Link><section className="flex-1 pb-8 pt-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0B57D0]">Referral impact</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em]">Your private impact at a glance.</h1><p className="mt-3 text-sm leading-6 text-slate-600">Only you can see this. Acceptances, pending decisions, and private messages from the requests you covered.</p>
    {hasAccepted ? <div className="mt-6 grid gap-3 sm:grid-cols-2"><ImpactStat label="Accepted referrals" value={summary.acceptedReferrals} detail="Candidates you chose to help" icon={CheckCircle2} accent="bg-emerald-50 text-emerald-700" valueClass="text-emerald-700" /><ImpactStat label="Pending decisions" value={summary.pendingRequests} detail="Waiting for your review" icon={Clock3} accent="bg-amber-50 text-amber-700" valueClass="text-amber-700" /><ImpactStat label="Unread messages" value={summary.unreadMessages} detail="Private notes from Job Seekers" icon={Inbox} accent="bg-blue-50 text-[#0B57D0]" valueClass="text-[#0B57D0]" /><ImpactStat label="Credits remaining" value={summary.creditsRemaining} detail="Available to accept new requests" icon={Wallet} accent="bg-slate-100 text-slate-600" /></div> : <div className="mt-6 rounded-2xl border border-dashed border-blue-200 bg-white p-6 text-center"><span aria-hidden="true" className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-[#0B57D0]"><Sparkles className="h-5 w-5" /></span><p className="mt-4 text-sm font-semibold text-slate-900">Your impact will show here once you accept your first referral</p><p className="mt-2 text-sm leading-6 text-slate-600">Open your inbox to review the private requests waiting at your company.</p><Link href="/inbox" className="mt-5 inline-flex items-center justify-center gap-2 rounded-lg bg-[#0B57D0] px-5 py-3 text-sm font-semibold text-white">Open my inbox <ArrowRight className="h-4 w-4" /></Link></div>}
    {hasAccepted && summary.recentAccepted.length ? <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Recent referrals</p><ul className="mt-4 space-y-3">{summary.recentAccepted.map(item => <li key={item.id} className="flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><CheckCircle2 className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-slate-800">{item.companyDomain}</span><span className="block text-xs text-slate-500">Accepted {relativeDays(item.acceptedAt)}</span></span></li>)}</ul></div> : null}
    {hasAccepted ? <div className="mt-6 grid gap-3 sm:grid-cols-2"><Link href="/inbox" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#0B57D0] px-5 py-3 text-sm font-semibold text-white">Open my inbox <ArrowRight className="h-4 w-4" /></Link><Link href="/share" className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700">Share skipwait.me</Link></div> : null}
    <p className="mt-8 flex items-start gap-2 text-xs leading-5 text-slate-500"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />Your identity stays hidden unless you accept a request. Job Seekers never see your work email.</p>
  </section></div></main>;
}
