import { Link } from "wouter";
import { ArrowLeft, BadgeCheck, CreditCard, FileKey2, HeartHandshake, ShieldCheck, UserRoundCheck } from "lucide-react";
import { Brand } from "@/components/Brand";

const safeguards = [
  { icon: UserRoundCheck, title: "Company-matched by design", body: "A referral request is visible only to verified employees at the company behind the role link." },
  { icon: FileKey2, title: "Documents stay private", body: "Your resume is available only to you and the Referrer assigned to your request. It is never public." },
  { icon: HeartHandshake, title: "Conversation opens after acceptance", body: "Job Seekers and Referrers can message only after the Referrer accepts that specific request." },
  { icon: CreditCard, title: "Hosted payment checkout", body: "Payment details are handled by the payment provider’s checkout. Referral decisions are always free for Referrers." },
];

export default function TrustPrivacy() {
  return <main className="min-h-screen bg-[#F5F4EF] px-5 py-5 text-[#191713] sm:px-6 sm:py-8"><div className="mx-auto max-w-3xl"><header className="flex items-center justify-between gap-4"><Brand /><Link href="/" className="inline-flex items-center gap-1 text-sm font-bold text-[#625D52] hover:text-[#191713]"><ArrowLeft className="h-4 w-4" />Back</Link></header><section className="mt-10 rounded-2xl border border-[#DBEAFE] bg-white p-6 sm:p-9"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#E8F0FE] text-[#191713]"><ShieldCheck className="h-5 w-5" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-[#191713]">Privacy & trust</p><h1 className="mt-3 max-w-2xl text-4xl font-semibold tracking-[-.02em]">A private handoff, not a public marketplace.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#625D52]">skipwait.me is designed to help one Job Seeker and the right verified employee move a referral forward with the least necessary exposure. We do not publish resumes, Referrer identities, or private request conversations.</p></section><section className="mt-5 grid gap-3 sm:grid-cols-2">{safeguards.map(({ icon: Icon, title, body }) => <article key={title} className="rounded-2xl border border-[#E2DDD2] bg-white p-5"><Icon className="h-5 w-5 text-[#191713]" /><h2 className="mt-4 text-base font-semibold text-[#191713]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#625D52]">{body}</p></article>)}</section><section className="mt-5 rounded-2xl border border-[#E2DDD2] bg-white p-6 sm:p-8"><div className="flex items-start gap-3"><BadgeCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-700" /><div><h2 className="text-lg font-semibold text-[#191713]">Your account controls</h2><p className="mt-2 text-sm leading-6 text-[#625D52]">When signed in, Settings gives you a copy of the personal data held for your account and lets you request account deletion review. Requests are reviewed rather than silently deleting records that may need reconciliation or security handling.</p><Link href="/settings" className="mt-5 inline-flex items-center justify-center rounded-lg bg-[#191713] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#2A2721]">Open privacy controls</Link></div></div></section><nav aria-label="Policies" className="mt-6 flex flex-wrap items-center justify-center gap-x-4 gap-y-2 text-xs font-semibold text-[#625D52]"><Link href="/terms" className="hover:text-[#191713]">Terms of Service</Link><Link href="/refunds" className="hover:text-[#191713]">Refunds & cancellation</Link><Link href="/support" className="hover:text-[#191713]">Support</Link></nav><p className="mx-auto mt-4 max-w-2xl text-center text-xs leading-5 text-[#625D52]">This page explains product safeguards and available controls. It is not a substitute for jurisdiction-specific legal notices or formal compliance certification.</p></div></main>;
}
