import {createHmac,randomBytes,timingSafeEqual} from "node:crypto";import type{Express,Request,Response}from"express";
type RealIdentity={account:{id:number;role?:"user"|"admin"}};export type SyntheticRole="seeker"|"referrer"|"admin"|"employer";type Payload={nonce:string;adminId:number;role:SyntheticRole;csrf:string;exp:number};
export type SmokeSnapshot={smokeMode:true;identity:{id:number;role:SyntheticRole;email:string;company:"Smoke Corp"};referralImpact:{acceptedReferrals:4};jobs:{jobs:never[]};opportunities:{opportunities:never[]};requests:{requests:Array<{id:number;jobTitle:string;company:string;status:"pending"}>};inbox:{requests:Array<{id:number;jobTitle:string;company:string;status:"pending"}>};impact:{accepted:number;helped:number};admin:{events:never[];users:Array<{id:number;name:string;email:string;role:"admin"}>};employer:{account:{id:number;companyName:"Smoke Corp";credits:number};talent:never[]}};
export type SmokeDeps={resolveIdentity:(req:Request)=>Promise<RealIdentity|undefined>;recordActivity?:(event:any)=>unknown};const COOKIE="skipwait_admin_smoke",CSRF_COOKIE="skipwait_smoke_csrf",TTL=15*60_000;const roles:SyntheticRole[]=["seeker","referrer","admin","employer"];const ids={seeker:-101,referrer:-102,admin:-103,employer:-104};const fixtures=new Map<string,SmokeSnapshot>(),activations=new Map<number,number[]>();
const cookies=(r:Request)=>Object.fromEntries(String(r.headers.cookie||"").split(";").map(v=>v.trim().split(/=(.*)/).slice(0,2)).filter(([k])=>k));const secret=()=>process.env.ADMIN_SMOKE_SECRET||"";const sign=(b:string)=>createHmac("sha256",secret()).update(b).digest("base64url");const encode=(p:Payload)=>{const b=Buffer.from(JSON.stringify(p)).toString("base64url");return`${b}.${sign(b)}`};
export function decodeSmokeCookie(raw?:string,now=Date.now()):Payload|undefined{if(!raw||!secret()||!raw.includes("."))return;const[b,s]=raw.split("."),e=sign(b);if(s.length!==e.length||!timingSafeEqual(Buffer.from(s),Buffer.from(e)))return;try{const p=JSON.parse(Buffer.from(b,"base64url").toString())as Payload;if(p.exp<=now||!roles.includes(p.role)||p.adminId<=0||!p.nonce||!p.csrf)return;return p}catch{return}}
const snapshot=(role:SyntheticRole):SmokeSnapshot=>{const id=ids[role],email=`${role}@smoke.invalid`;return{smokeMode:true,identity:{id,role,email,company:"Smoke Corp"},referralImpact:{acceptedReferrals:4},jobs:{jobs:[]},opportunities:{opportunities:[]},requests:{requests:[{id:-201,jobTitle:"Synthetic Product Designer",company:"Smoke Corp",status:"pending"}]},inbox:{requests:[{id:-202,jobTitle:"Synthetic Design Lead",company:"Smoke Corp",status:"pending"}]},impact:{accepted:1,helped:1},admin:{events:[],users:[{id,name:"Synthetic Admin",email:"admin@smoke.invalid",role:"admin"}]},employer:{account:{id,companyName:"Smoke Corp",credits:3},talent:[]}}};
const csrfOk=(r:Request,p?:Payload)=>{const c=cookies(r),v=String(r.header("x-csrf-token")||r.body?.csrf||"");return!!(v&&c[CSRF_COOKIE]===v&&(!p||p.csrf===v))};const active=(r:Request,res:Response)=>{const p=decodeSmokeCookie(cookies(r)[COOKIE]);if(!p||!fixtures.has(p.nonce)){res.status(401).json({error:"Smoke session is invalid or expired"});return}return p};
export function registerAdminSmokeFixture(app:Express,deps:SmokeDeps){
 app.get("/api/admin/smoke/status",(r,res)=>{if(process.env.ENABLE_ADMIN_SMOKE_FIXTURE!=="true")return res.status(404).json({error:"Not found"});const p=decodeSmokeCookie(cookies(r)[COOKIE]),csrf=p?.csrf||randomBytes(24).toString("base64url");res.append("Set-Cookie",`${CSRF_COOKIE}=${csrf}; Path=/; Max-Age=900; Secure; SameSite=Strict`).set("Cache-Control","no-store").json({enabled:true,active:!!(p&&fixtures.has(p.nonce)),role:p?.role,identity:p?fixtures.get(p.nonce)?.identity:undefined,csrf})});
 app.post("/api/admin/smoke/activate",async(r,res)=>{if(process.env.ENABLE_ADMIN_SMOKE_FIXTURE!=="true")return res.status(404).json({error:"Not found"});if(!secret())return res.status(503).json({error:"Smoke secret is not configured"});const who=await deps.resolveIdentity(r);if(!who||who.account.role!=="admin")return res.status(403).json({error:"Administrator access is required"});if(!csrfOk(r))return res.status(403).json({error:"CSRF validation failed"});const now=Date.now(),hits=(activations.get(who.account.id)||[]).filter(t=>now-t<60_000);if(hits.length>=5)return res.status(429).json({error:"Smoke activation rate limit exceeded"});hits.push(now);activations.set(who.account.id,hits);const role=r.body?.role as SyntheticRole;if(!roles.includes(role))return res.status(400).json({error:"Invalid synthetic role"});const p={nonce:randomBytes(18).toString("base64url"),adminId:who.account.id,role,csrf:cookies(r)[CSRF_COOKIE],exp:now+TTL};fixtures.set(p.nonce,snapshot(role));res.append("Set-Cookie",`${COOKIE}=${encode(p)}; Path=/; Max-Age=900; HttpOnly; Secure; SameSite=Strict`);void deps.recordActivity?.({actorUserId:who.account.id,action:"admin.smoke_activated",outcome:"success",resourceType:"smoke_fixture",metadata:{role}});res.json({active:true,role})});
 app.get("/api/admin/smoke/snapshot",(r,res)=>{const p=active(r,res);if(p)res.json(fixtures.get(p.nonce))});
 app.post("/api/admin/smoke/action",(r,res)=>{const p=active(r,res);if(!p)return;if(!csrfOk(r,p))return res.status(403).json({error:"CSRF validation failed"});const action=String(r.body?.action||"");if(!["save_request","withdraw_request","claim_request","mark_notification_read"].includes(action))return res.status(409).json({smokeMode:true,error:"Unknown or live mutation is denied in smoke mode"});res.json({smokeMode:true,ok:true,action})});
 app.post("/api/admin/smoke/reset",(r,res)=>{const p=active(r,res);if(!p)return;if(!csrfOk(r,p))return res.status(403).json({error:"CSRF validation failed"});fixtures.set(p.nonce,snapshot(p.role));res.json({smokeMode:true,reset:true})});
 app.post("/api/admin/smoke/exit",(r,res)=>{const p=active(r,res);if(!p)return;if(!csrfOk(r,p))return res.status(403).json({error:"CSRF validation failed"});fixtures.delete(p.nonce);res.append("Set-Cookie",`${COOKIE}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict`);void deps.recordActivity?.({actorUserId:p.adminId,action:"admin.smoke_exited",outcome:"success",resourceType:"smoke_fixture"});res.json({active:false})});
 app.all("/api/admin/smoke/*",(r,res)=>res.status(409).json({smokeMode:true,error:"Unknown smoke fixture endpoint or mutation is denied"}));
}
export const __smokeTest={fixtures,activations,ids,snapshot};
