import express from "express";import request from "supertest";import {beforeEach,describe,expect,it,vi} from "vitest";import {registerAdminSmokeFixture,__smokeTest} from "./adminSmokeFixture";
const admin={account:{id:7,role:"admin" as const}},member={account:{id:8,role:"user" as const}};
const appFor=(who:any=admin,record=vi.fn())=>{const app=express();app.use(express.json());registerAdminSmokeFixture(app,{resolveIdentity:async()=>who,recordActivity:record});app.post("/api/payments/refund",(_q,r)=>r.json({live:true}));app.get("/api/live-db",(_q,r)=>r.json({liveDb:true}));return app};
const csrf=async(app:any)=>{const r=await request(app).get("/api/admin/smoke/status");return {token:r.body.csrf,cookie:r.headers["set-cookie"][0].split(";")[0]}};
const activate=async(app:any,role="seeker")=>{const c=await csrf(app);const r=await request(app).post("/api/admin/smoke/activate").set("Cookie",c.cookie).set("x-csrf-token",c.token).send({role});return {r,cookie:r.headers["set-cookie"][0].split(";")[0],csrf:c}};
beforeEach(()=>{process.env.ENABLE_ADMIN_SMOKE_FIXTURE="true";process.env.ADMIN_SMOKE_SECRET="test-secret-long-enough";__smokeTest.fixtures.clear()});
describe("protected admin smoke fixture",()=>{
 it("is 404 with flag off and rejects non-admin",async()=>{process.env.ENABLE_ADMIN_SMOKE_FIXTURE="false";expect((await request(appFor()).get("/api/admin/smoke/status")).status).toBe(404);process.env.ENABLE_ADMIN_SMOKE_FIXTURE="true";const app=appFor(member),c=await csrf(app);expect((await request(app).post("/api/admin/smoke/activate").set("Cookie",c.cookie).set("x-csrf-token",c.token).send({role:"seeker"})).status).toBe(403)});
 it("uses negative synthetic IDs and never calls a database or provider",async()=>{const provider=vi.fn(),app=appFor(admin,provider),a=await activate(app,"referrer");expect(a.r.status).toBe(200);expect(a.r.headers["set-cookie"][0]).toContain("HttpOnly; Secure; SameSite=Strict");const f=await request(app).get("/api/admin/smoke/fixture").set("Cookie",a.cookie);expect(f.body.data.user.id).toBeLessThan(0);expect(f.body.data.user.email).toBe("referrer@smoke.invalid");expect(provider).toHaveBeenCalledTimes(1)});
 it("rejects tampered and expired cookies",async()=>{const app=appFor(),a=await activate(app);expect((await request(app).get("/api/admin/smoke/fixture").set("Cookie",a.cookie+"x")).status).toBe(401);const raw=a.cookie.split("=")[1],body=raw.split(".")[0],payload=JSON.parse(Buffer.from(body,"base64url").toString());payload.exp=1;const expired=`skipwait_admin_smoke=${Buffer.from(JSON.stringify(payload)).toString("base64url")}.${raw.split(".")[1]}`;expect((await request(app).get("/api/admin/smoke/fixture").set("Cookie",expired)).status).toBe(401)});
 it("denies destructive endpoints and isolates reset/outside state",async()=>{const app=appFor(),a=await activate(app);expect((await request(app).post("/api/payments/refund").set("Cookie",a.cookie)).status).toBe(409);const adapted=await request(app).get("/api/live-db").set("Cookie",a.cookie);expect(adapted.body.smokeMode).toBe(true);expect(adapted.body.liveDb).toBeUndefined();const outside=await request(app).get("/api/admin/smoke/fixture");expect(outside.status).toBe(401);const reset=await request(app).post("/api/admin/smoke/reset").set("Cookie",[a.cookie,a.csrf.cookie]).set("x-csrf-token",a.csrf.token).send({csrf:a.csrf.token});expect(reset.status).toBe(200);expect(reset.body.data.requests.every((x:any)=>x.id<0)).toBe(true)});
});
