import { invokeLLM, listLLMModels } from "./_core/llm";

type WorkspaceContext = { profile?: { headline?: string | null; skills?: string | null; experience?: string | null; accountType?: string | null } | null; jobs: Array<{ id: number; title: string; company: string; location: string; seniority: string; workMode: string; description: string }>; referrers: Array<{ userId: number; name: string | null; company: string | null; title: string | null; expertise: string | null; capacity: number | null }>; savedRoles: Array<{ title: string; company: string; seniority: string }>; referrals: Array<{ jobTitle: string; company: string; status: string; updatedAt: Date | null }>; recentMessageCount: number; stats: { savedRoles: number; activeReferralRequests: number; incomingReferralRequests: number; introductionsMade: number; conversationsStarted: number; peopleHired: number } };
let selectedModel: string | undefined;
async function getModel() { if (selectedModel) return selectedModel; const { data } = await listLLMModels(); selectedModel = data.find(model => model.id === "gpt-5-mini")?.id || data.find(model => model.id.startsWith("gpt-5"))?.id || data[0]?.id; return selectedModel; }
async function ask(system: string, user: string, fallback: string) { try { const response = await invokeLLM({ model: await getModel(), messages: [{ role: "system", content: system }, { role: "user", content: user }], maxTokens: 700 }); const content = response.choices[0]?.message?.content; return (typeof content === "string" ? content.trim() : "") || fallback; } catch (error) { console.warn("[Bridge AI] request failed", error); return fallback; } }
function contextText(context: WorkspaceContext) { return JSON.stringify({ profile: context.profile, openJobs: context.jobs, availableReferrers: context.referrers, savedRoles: context.savedRoles, referralRequests: context.referrals, recentMessageCount: context.recentMessageCount, metrics: context.stats }); }

export async function runCareerCopilot(input: { message: string; context: WorkspaceContext }) { return ask("You are Bridge Copilot, an incisive but warm career strategist. Ground every recommendation strictly in the supplied member, role, Referrer, message, and Referral Request context. Never invent openings, people, details, or outcomes. Give one concrete next move and explain the evidence in a short paragraph with up to three bullets.", `Live Bridge context:\n${contextText(input.context)}\n\nMember request: ${input.message}`, "Tell me which goal or opportunity matters most today. I’ll help you turn the available context into a clear next step."); }
export async function draftReferralPitch(input: { jobTitle: string; company: string; referrerName: string; notes: string; profile?: { headline?: string | null; skills?: string | null; experience?: string | null } | null }) { const profile = `Profile headline: ${input.profile?.headline || "Not provided"}. Skills: ${input.profile?.skills || "Not provided"}. Experience: ${input.profile?.experience || "Not provided"}.`; return ask("You write concise, honest Referral Request drafts. Write a thoughtful 120–180 word first-person pitch. Do not exaggerate credentials, use placeholders, or imply the Referrer owes an introduction. Mention the role, why it fits, and a low-pressure invitation to review.", `${profile}\nRole: ${input.jobTitle} at ${input.company}. Referrer: ${input.referrerName}. Job Seeker notes: ${input.notes}`, `Hi ${input.referrerName}, I’m interested in the ${input.jobTitle} role at ${input.company}. ${input.notes} If you have a moment to review my background, I’d be grateful for your perspective on whether an introduction would make sense. Thank you for considering it.`); }
export function hiringManagerEmailFallback(input: { candidateName: string; targetRoleUrl: string; accomplished?: string; measuredBy?: string; byDoing?: string }) { const evidence = input.accomplished && input.measuredBy && input.byDoing ? `${input.candidateName} ${input.accomplished}, measured by ${input.measuredBy}, by ${input.byDoing}.` : "I would encourage you to review their attached materials and assess their experience against the team’s current needs."; return `Subject: Referral — ${input.candidateName}\n\nHi [Hiring Manager Name],\n\nI’d like to recommend ${input.candidateName} for the opportunity here: ${input.targetRoleUrl}\n\n${evidence}\n\nI believe their background is worth your consideration, and I’ve attached their supporting documents for review. I’m happy to share additional context if useful.\n\nBest,\n[Your Name]`; }
export async function draftHiringManagerEmail(input: { candidateName: string; targetRoleUrl: string; accomplished?: string; measuredBy?: string; byDoing?: string }) { const fallback = hiringManagerEmailFallback(input); const evidence = input.accomplished && input.measuredBy && input.byDoing ? `Candidate evidence, supplied by the Referrer: ${input.accomplished}; measured by ${input.measuredBy}; by ${input.byDoing}.` : "No verified accomplishment has been supplied. Do not invent any achievement, metric, experience, or relationship."; return ask("You write exact, concise employee-to-hiring-manager referral emails. Return only the finished plaintext email, including a Subject line. Use only supplied facts. If no verified evidence is provided, be appropriately general rather than inventing facts. Preserve the candidate name and target role URL exactly. Keep it under 170 words, professional, warm, and ready for the Referrer to edit before sending.", `Candidate: ${input.candidateName}\nTarget Role URL: ${input.targetRoleUrl}\n${evidence}`, fallback); }
export async function summarizeReferralFit(input: { candidateName: string; jobTitle: string; company: string; personalPitch: string }) { return ask("You are a careful referral-review assistant. Give a compact neutral candidate brief with exactly three bullets: evidence of fit, question to clarify, and respectful suggested response. Do not decide for the Referrer and do not infer facts outside the provided text.", `Candidate: ${input.candidateName}. Role: ${input.jobTitle} at ${input.company}. Personal pitch: ${input.personalPitch}`, "• **Evidence of fit:** The candidate has articulated a considered interest in this role.\n• **Question to clarify:** Ask about the specific experience most relevant to the team’s current needs.\n• **Suggested response:** Thank them for the context and share whether an introduction feels appropriate."); }
export async function matchReferrers(input: { jobTitle: string; company: string; context: WorkspaceContext }) { const candidates = input.context.referrers.filter(referrer => (referrer.capacity ?? 0) > 0); const fallback = { strategy: "Choose a Referrer whose expertise is closest to the role and send a concise note that asks for perspective before an introduction.", matches: candidates.slice(0, 3).map((candidate, index) => ({ userId: candidate.userId, name: candidate.name || "Available Referrer", rationale: index === 0 ? "Their stated expertise and availability are the strongest available context match." : "They have relevant listed expertise and capacity to review a thoughtful request." })) };
  const raw = await ask("You are Bridge’s referral-matching assistant. Rank only the provided Referrers for the supplied role. Use their stated company, title, expertise, and capacity. Do not fabricate connections. Return valid JSON only with a strategy string and a matches array of up to three objects: userId number, name string, rationale string.", `Role: ${input.jobTitle} at ${input.company}.\nContext: ${contextText(input.context)}`, JSON.stringify(fallback));
  try { const parsed = JSON.parse(raw) as typeof fallback; return { strategy: String(parsed.strategy || fallback.strategy), matches: Array.isArray(parsed.matches) ? parsed.matches.filter(match => typeof match.userId === "number" && typeof match.name === "string" && typeof match.rationale === "string").slice(0, 3) : fallback.matches }; } catch { return fallback; }
}
export async function createProactiveBrief(input: { context: WorkspaceContext }) { const fallback = { items: [{ title: input.context.savedRoles.length ? "Review your strongest saved role" : "Set your direction", body: input.context.savedRoles.length ? `You have ${input.context.savedRoles.length} saved role${input.context.savedRoles.length === 1 ? "" : "s"}. Pick one to examine with Copilot.` : "Add a role or update your profile so Bridge can reason from better context.", action: "Explore with Copilot" }, { title: input.context.referrals.length ? "Move one Referral Request forward" : "Build your first introduction path", body: input.context.referrals.length ? `You have ${input.context.referrals.length} active or historical Referral Request${input.context.referrals.length === 1 ? "" : "s"} in view.` : "Find a relevant role, then let Copilot help you shape a respectful ask.", action: "Review pathways" }, { title: input.context.recentMessageCount ? "Prepare for your conversation" : "Keep room for context", body: input.context.recentMessageCount ? `There ${input.context.recentMessageCount === 1 ? "is" : "are"} ${input.context.recentMessageCount} message${input.context.recentMessageCount === 1 ? "" : "s"} in your workspace.` : "Bridge will surface conversation context here when a relationship needs your attention.", action: "Open messages" }] };
  const raw = await ask("You are Bridge Copilot. Create a short proactive work brief from the supplied live workspace context. Return valid JSON only as {items:[{title,body,action}]} with exactly three items. Every item must refer only to real counts or data in the context, suggest a low-pressure next move, and never claim a person is waiting unless the context says so.", contextText(input.context), JSON.stringify(fallback));
  try { const parsed = JSON.parse(raw) as typeof fallback; return { items: Array.isArray(parsed.items) && parsed.items.length === 3 ? parsed.items.map(item => ({ title: String(item.title), body: String(item.body), action: String(item.action) })) : fallback.items }; } catch { return fallback; }
}
