import express from"express";import request from"supertest";import{describe,expect,it,vi}from"vitest";import{registerJobLinkPreviewRoutes}from"./jobLinkPreviewRoutes";import{isPublicAddress,previewJobLink}from"./jobLinkPreview";import{verifiedEmployerDomainFromCandidates}from"./employerRouting";
describe("job-link preview",()=>{it.each(["127.0.0.1","10.0.0.1","169.254.1.1","::1","fc00::1"])("blocks %s",a=>expect(isPublicAddress(a)).toBe(false));it("shares final resolver and does not mutate",async()=>{const resolve=vi.fn(async()=>"acme.com"),mutate=vi.fn();const app=express();registerJobLinkPreviewRoutes(app,{resolveEmployerDomainFromTargetUrl:resolve,preview:async(url,r)=>({canonicalUrl:url,status:"fresh",employerConfidence:"direct-domain",companyDomain:await r(url),reason:"ok",recoveryAction:"continue"})});const response=await request(app).post("/api/job-link/preview").send({url:"https://careers.acme.com/jobs/1"});expect(response.body.companyDomain).toBe("acme.com");expect(resolve).toHaveBeenCalledOnce();expect(mutate).not.toHaveBeenCalled();expect(response.headers["cache-control"]).toBe("public, max-age=120");expect(Object.keys(response.body).sort()).toEqual(["canonicalUrl","companyDomain","employerConfidence","reason","recoveryAction","status"].sort())});it("fails prefix evidence closed",()=>{for(const [c,d]of[["meta","metaverse.com"],["check","checkout.com"],["stripe","stripetest.com"]])expect(verifiedEmployerDomainFromCandidates([c],[d])).toBeUndefined();expect(verifiedEmployerDomainFromCandidates(["acme"],["acme.com","acme.io"])).toBeUndefined()});it("marks unresolved as ambiguous before resume",async()=>{const result=await previewJobLink("https://jobs.lever.co/meta/1",async()=>undefined);expect(result.employerConfidence).toMatch(/ambiguous|unreachable/);expect(result.recoveryAction).toMatch(/Confirm|Check/)})});

describe("preview coalescing",()=>{it("shares fetch and resolver work for identical public URLs",async()=>{const {resetJobLinkPreviewCache}=await import("./jobLinkPreview");resetJobLinkPreviewCache();let release!:()=>void;const gate=new Promise<void>(r=>release=r);const fetcher=vi.fn(async()=>{await gate;return{canonicalUrl:"https://careers.coalesce.test/1",body:""}});const resolve=vi.fn(async()=>"coalesce.test");const a=previewJobLink("https://careers.coalesce.test/1",resolve,fetcher);const b=previewJobLink("https://careers.coalesce.test/1",resolve,fetcher);release();await Promise.all([a,b]);expect(fetcher).toHaveBeenCalledOnce();expect(resolve).toHaveBeenCalledOnce()});it("removes rejected promises so a retry can run",async()=>{const {resetJobLinkPreviewCache}=await import("./jobLinkPreview");resetJobLinkPreviewCache();const resolve=vi.fn(async()=>{throw Error("resolver")});const fetcher=vi.fn(async()=>{throw Error("network")});await previewJobLink("https://careers.retry.test/1",resolve,fetcher);resetJobLinkPreviewCache();await previewJobLink("https://careers.retry.test/1",resolve,fetcher);expect(fetcher).toHaveBeenCalledTimes(2)});it("uses only a normalized public URL as its cache key and public fields as values",async()=>{const {resetJobLinkPreviewCache}=await import("./jobLinkPreview");resetJobLinkPreviewCache();const result=await previewJobLink("https://careers.public.test/1#private-token",async()=>"public.test",async()=>({canonicalUrl:"https://careers.public.test/1",body:""}));expect(result.canonicalUrl).toBe("https://careers.public.test/1");expect(JSON.stringify(result)).not.toMatch(/token|user|auth/i)})});


describe("reachable employer evidence",()=>{
 it("does not trust a hostname-derived employer when DNS/page fetch fails",async()=>{const result=await previewJobLink("https://careers.no-such-company-zzz987.com/jobs/12345",async()=>"no-such-company-zzz987.com",async()=>{throw Error("dns")});expect(result).toMatchObject({status:"unreachable",employerConfidence:"unreachable"});expect(result.companyDomain).toBeUndefined()});
 it("treats a safely reached oversized direct careers page as reachable without parsing its body",async()=>{const result=await previewJobLink("https://careers.google.com",async()=>"google.com",async url=>({canonicalUrl:"https://www.google.com/about/careers/applications/",body:""}));expect(result).toMatchObject({status:"fresh",companyDomain:"google.com"})});
 it("allows public Greenhouse company boards through the pinned fetcher policy",async()=>{const source=await import("node:fs").then(fs=>fs.readFileSync(new URL("./jobLinkPreview.ts",import.meta.url),"utf8"));expect(source).toContain('url.hostname==="boards.greenhouse.io"');expect(source).toContain('url.hostname==="job-boards.greenhouse.io"')});
 it("resolves a reachable Greenhouse board when employer evidence is returned",async()=>{const result=await previewJobLink("https://boards.greenhouse.io/stripe",async()=>"stripe.com",async()=>({canonicalUrl:"https://stripe.com/jobs/search",body:"Stripe jobs"}));expect(result).toMatchObject({status:"fresh",companyDomain:"stripe.com"})});
});
