import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
const db=readFileSync(new URL("./db.ts",import.meta.url),"utf8");const routes=readFileSync(new URL("./privateReferralRoutes.ts",import.meta.url),"utf8");const schema=readFileSync(new URL("../drizzle/schema.ts",import.meta.url),"utf8");
describe("referral review delivery outbox",()=>{
 it("creates stable grants and delivery state with the request",()=>{const create=db.slice(db.indexOf("export async function createCompanyReferralRequest"),db.indexOf("const reviewEmailLifetimeMs"));expect(create).toContain("referrerReviewEmailLinks");expect(create).toContain("referralReviewDeliveries");expect(schema).toContain("referral_review_delivery_recipient_unique");});
 it("never sends on request replay and never rotates grants implicitly",()=>{expect(routes).toContain("!result.replayed && deps.prepareReferrerReviewEmailNotifications");const links=db.slice(db.indexOf("export async function createReferrerReviewEmailLinks"),db.indexOf("// ---- Opt-in private Slack"));expect(links).not.toContain("onDuplicateKeyUpdate({ set: { linkToken");expect(links).not.toContain("consumedAt: null");});
 it("leases email and Slack attempts and records sent, failed or unknown",()=>{expect(db).toContain("claimReferralReviewDelivery");expect(db).toContain("completeReferralReviewDelivery");expect(routes).toContain('claimReferralReviewDelivery(result.requestId,link.referrerId,"email"');expect(routes).toContain('claimReferralReviewDelivery(result.requestId,target.referrerId,"slack"');expect(routes).toContain('status:"unknown"');expect(db).toContain("attemptCount>=5");});
 it("rotates only through an explicit audited atomic action",()=>{const rotate=db.slice(db.indexOf("export async function rotateReferralReviewGrant"),db.indexOf("// ---- Opt-in private Slack"));expect(rotate).toContain("db.transaction");expect(rotate).toContain('status:"revoked"');expect(rotate).toContain("referralReviewGrantRotations");expect(rotate).toContain("grantVersion:toVersion");expect(rotate).toContain("consumedAt:null");});
});
