import { afterAll, beforeAll, describe, expect, it } from "vitest";
import mysql, { type Pool, type PoolConnection } from "mysql2/promise";

const enabled=process.env.WALLET_MYSQL_ACCEPTANCE==="1";
const suite=enabled?describe:describe.skip;
let pool:Pool;
const userId=901;
async function reset(monthly=1,purchased=0,cycle="2026-09") { await pool.query("DELETE FROM txs");await pool.query("DELETE FROM requests");await pool.query("DELETE FROM wallets");await pool.query("INSERT INTO wallets(user_id,role,monthly,purchased,cycle_key) VALUES(?, 'job_seeker', ?, ?, ?)",[userId,monthly,purchased,cycle]); }
async function submit(key:string,fingerprint:string,failAt?:string){const cx=await pool.getConnection();try{await cx.beginTransaction();const [[wallet]]:any=await cx.query("SELECT * FROM wallets WHERE user_id=? AND role='job_seeker' FOR UPDATE",[userId]);const [[existing]]:any=await cx.query("SELECT * FROM requests WHERE user_id=? AND idem_key=? FOR UPDATE",[userId,key]);if(existing){if(existing.fingerprint!==fingerprint)throw Object.assign(new Error("conflict"),{code:"CONFLICT"});await cx.commit();return existing.id;}if(wallet.monthly+wallet.purchased<1)throw Object.assign(new Error("insufficient"),{code:"INSUFFICIENT"});const source=wallet.monthly>0?"monthly_allowance":"purchased_balance";const [created]:any=await cx.query("INSERT INTO requests(user_id,idem_key,fingerprint,status) VALUES(?,?,?,'pending')",[userId,key,fingerprint]);if(failAt==="request")throw new Error("injected");const nextMonthly=source==="monthly_allowance"?wallet.monthly-1:wallet.monthly;const nextPurchased=source==="purchased_balance"?wallet.purchased-1:wallet.purchased;await cx.query("UPDATE wallets SET monthly=?,purchased=? WHERE id=?",[nextMonthly,nextPurchased,wallet.id]);if(failAt==="wallet")throw new Error("injected");const [debit]:any=await cx.query("INSERT INTO txs(user_id,token_count,kind,source,source_cycle,reference_id,idem_key) VALUES(?,-1,'direct_request',?,?,?,?)",[userId,source,wallet.cycle_key,String(created.insertId),key]);await cx.query("UPDATE requests SET debit_id=? WHERE id=?",[debit.insertId,created.insertId]);if(failAt==="ledger")throw new Error("injected");await cx.commit();return created.insertId;}catch(e){await cx.rollback();throw e;}finally{cx.release();}}
async function withdraw(requestId:number){const cx=await pool.getConnection();try{await cx.beginTransaction();const [[request]]:any=await cx.query("SELECT * FROM requests WHERE id=? FOR UPDATE",[requestId]);if(request.status==='withdrawn'){await cx.commit();return;}const [[wallet]]:any=await cx.query("SELECT * FROM wallets WHERE user_id=? FOR UPDATE",[request.user_id]);const [[debit]]:any=await cx.query("SELECT * FROM txs WHERE id=? FOR UPDATE",[request.debit_id]);const [[reversal]]:any=await cx.query("SELECT id FROM txs WHERE reverses_id=?",[debit.id]);if(!reversal){let monthly=wallet.monthly,purchased=wallet.purchased,count=1;if(debit.source==='purchased_balance')purchased++;else if(debit.source_cycle===wallet.cycle_key)monthly++;else count=0;await cx.query("UPDATE wallets SET monthly=?,purchased=? WHERE id=?",[monthly,purchased,wallet.id]);await cx.query("INSERT INTO txs(user_id,token_count,kind,source,source_cycle,reference_id,reverses_id) VALUES(?,?,'withdrawal_refund',?,?,?,?)",[request.user_id,count,debit.source,debit.source_cycle,String(request.id),debit.id]);}await cx.query("UPDATE requests SET status='withdrawn' WHERE id=?",[request.id]);await cx.commit();}catch(e){await cx.rollback();throw e;}finally{cx.release();}}
async function counts(){const [[w]]:any=await pool.query("SELECT monthly,purchased,cycle_key FROM wallets WHERE user_id=?",[userId]);const [[r]]:any=await pool.query("SELECT COUNT(*) n FROM requests");const [[t]]:any=await pool.query("SELECT COUNT(*) n FROM txs WHERE kind='direct_request'");return{w,r:r.n,t:t.n};}

suite("atomic wallet/referral MySQL acceptance",()=>{beforeAll(async()=>{const u=new URL(process.env.WALLET_MYSQL_URL!);pool=mysql.createPool({host:u.hostname,port:Number(u.port||3306),user:decodeURIComponent(u.username),password:decodeURIComponent(u.password),database:u.pathname.slice(1),ssl:{rejectUnauthorized:true}});await pool.query("DROP TABLE IF EXISTS txs,requests,wallets");await pool.query("CREATE TABLE wallets(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,role VARCHAR(20),monthly INT NOT NULL,purchased INT NOT NULL,cycle_key VARCHAR(16),UNIQUE(user_id,role)) ENGINE=InnoDB");await pool.query("CREATE TABLE requests(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,idem_key VARCHAR(64),fingerprint VARCHAR(64),status VARCHAR(20),debit_id INT,UNIQUE(user_id,idem_key)) ENGINE=InnoDB");await pool.query("CREATE TABLE txs(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,token_count INT,kind VARCHAR(32),source VARCHAR(32),source_cycle VARCHAR(16),reference_id VARCHAR(80),idem_key VARCHAR(64),reverses_id INT,UNIQUE(user_id,idem_key,kind),UNIQUE(reverses_id)) ENGINE=InnoDB");});afterAll(async()=>{await pool?.end();});
 it.each([2,20])("allows one of %i parallel different-key spends with one credit",async n=>{await reset();const results=await Promise.allSettled(Array.from({length:n},(_,i)=>submit(`different-key-${n}-${i}`,`fp-${i}`)));expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(await counts()).toMatchObject({w:{monthly:0,purchased:0},r:1,t:1});});
 it("collapses 20 parallel same-key submissions",async()=>{await reset();const ids=await Promise.all(Array.from({length:20},()=>submit("same-key-000000000000","same-fingerprint")));expect(new Set(ids).size).toBe(1);expect(await counts()).toMatchObject({r:1,t:1});});
 it("rejects changed payload replay",async()=>{await reset();await submit("conflict-key-000000","first");await expect(submit("conflict-key-000000","changed")).rejects.toMatchObject({code:"CONFLICT"});});
 it.each(["request","wallet","ledger"])("rolls back injected failure after %s",async step=>{await reset();await expect(submit(`failure-key-${step}-0000`,"fp",step)).rejects.toThrow("injected");expect(await counts()).toMatchObject({w:{monthly:1,purchased:0},r:0,t:0});});
 it("handles rollover under the wallet lock",async()=>{await reset(0,1,"2026-10");await submit("rollover-key-000000","fp");expect(await counts()).toMatchObject({w:{monthly:0,purchased:0,cycle_key:"2026-10"}});});
 it("withdraws once and restores the exact purchased source",async()=>{await reset(0,1);const id=await submit("withdraw-key-000000","fp");await Promise.all([withdraw(id),withdraw(id)]);const c=await counts();expect(c.w).toMatchObject({monthly:0,purchased:1});const [[x]]:any=await pool.query("SELECT COUNT(*) n FROM txs WHERE kind='withdrawal_refund'");expect(x.n).toBe(1);});
 it("expires an old-cycle monthly refund without converting it",async()=>{await reset(1,0,"2026-09");const id=await submit("expiry-key-00000000","fp");await pool.query("UPDATE wallets SET cycle_key='2026-10',monthly=3 WHERE user_id=?",[userId]);await withdraw(id);const [[w]]:any=await pool.query("SELECT monthly,purchased FROM wallets WHERE user_id=?",[userId]);expect(w).toMatchObject({monthly:3,purchased:0});const [[x]]:any=await pool.query("SELECT token_count FROM txs WHERE kind='withdrawal_refund'");expect(x.token_count).toBe(0);});
});
