import { ConsentBanner } from "@/components/consent-banner";
import { Link } from "@tanstack/react-router";
import { ArrowUpRight, ArrowRight, ShieldCheck, LockKeyhole, HeartHandshake, Check, Plus, Minus, Menu, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import hero from "@/assets/launch-door.jpg";
import { VisualJourney } from "@/components/visual-journey";
import { launchCompanies } from "@/lib/marketplace-data";

const questions = [
  ["Are job referrals really free?", "Yes. No payments between seekers and referrers, no referral commission, and no paid priority. A referral is a voluntary introduction, not a purchase."],
  ["Do I need to know someone at the company?", "No existing connection is required. Explore companies with available referrers, find a relevant role, and send a thoughtful request. Each referrer chooses which requests to accept."],
  ["What does verification mean?", "Work-email verification confirms ownership of an address on an approved company domain. It does not prove current employment or imply an employer’s endorsement."],
  ["Does a referral guarantee an interview?", "No. A referral is an introduction, not a promise. Employers independently decide who to interview and hire."],
];

export function LaunchPage() {
  const [menu, setMenu] = useState(false);
  const [faq, setFaq] = useState<number | null>(0);
  return <div className="launch-page"><ConsentBanner />
    <header className="launch-header"><Link className="wordmark" to="/">SkipWait<span className="brand-dot">.</span></Link><nav aria-label="Website navigation" className={menu ? "launch-nav open" : "launch-nav"}><Link to="/explore" onClick={() => setMenu(false)}>Explore companies</Link><Link to="/referrer" onClick={() => setMenu(false)}>For referrers</Link><Link to="/safety" onClick={() => setMenu(false)}>Help & safety</Link><Link className="launch-mobile-signin" to="/sign-in" onClick={() => setMenu(false)}>Sign in <ArrowRight size={14} /></Link></nav><div className="launch-header-actions"><Button asChild variant="ghost" className="launch-signin"><Link to="/sign-in">Sign in</Link></Button><Button asChild variant="outline"><Link to="/explore">Explore <ArrowUpRight /></Link></Button><Button className="launch-menu" variant="ghost" size="icon" aria-label={menu ? "Close navigation" : "Open navigation"} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</Button></div></header>
    <main>
      <section className="launch-hero"><img className="launch-hero-image" src={hero} alt="An open blue door with a yellow path leading through it" width={1600} height={1008} fetchPriority="high" /><div className="launch-hero-copy"><span className="launch-kicker"><span />INTRODUCING SKIPWAIT</span><h1>Free job referrals.<br />A warmer way in<span className="brand-dot">.</span></h1><p>Connect with people inside the companies you want to join.<br className="desktop-break" /> A real introduction. Not another application into the unknown.</p><Button asChild><Link to="/explore">Explore companies <ArrowUpRight /></Link></Button><Link className="hero-secondary" to="/referrer">Already on the inside? Become a referrer <ArrowRight size={14} /></Link><div className="hero-assurances"><span><Check size={13} />Referrals are free</span><span><Check size={13} />Explore before signing in</span></div></div><span className="hero-side-note">YOUR NEXT CHAPTER STARTS WITH A CONNECTION.</span></section>
      <section className="launch-trust-strip" aria-label="Our commitments"><span><HeartHandshake />No referral fees.</span><span><LockKeyhole />Private by default.</span><span><ShieldCheck />No job guarantees.</span></section>
      <section className="launch-section launch-companies"><div className="section-intro"><span className="eyebrow">OPEN DOORS AT LAUNCH</span><h2>Start somewhere real.</h2><p>People at these companies have told SkipWait they are open to referral requests. Availability can change, and every person chooses each ask.</p></div><div className="launch-company-row">{launchCompanies.map(company => <Link key={company.slug} to="/explore/$slug" params={{ slug: company.slug }}><span className="company-mark">{company.initials}</span><strong>{company.name}</strong><ArrowUpRight /></Link>)}</div><Link className="text-link" to="/explore">Explore all open doors <ArrowRight /></Link></section>
      <section className="launch-section launch-steps"><div className="section-intro"><span className="eyebrow">THREE STEPS. ONE OPEN DOOR.</span><h2>Your way in,<br />made simple.</h2><p>Find a company. Make an ask. Meet someone inside.</p></div><VisualJourney /><Link className="text-link" to="/explore">Find your way in <ArrowRight size={16} /></Link></section>
      <section className="launch-referrer-band"><div className="launch-section referrer-band-inner"><span className="eyebrow">FOR THE PEOPLE ON THE INSIDE</span><div className="referrer-band-grid"><div><h2>You could be someone’s<br />first open door.</h2><p>A few minutes of your time could help someone take their next step. Choose who you help. Set your own capacity. Keep your identity private until you accept.</p><Button variant="outline" asChild><Link to="/referrer">Become a referrer <ArrowUpRight /></Link></Button></div><div className="referrer-commitments"><span><Check />Your name is never public.</span><span><Check />You choose every connection.</span><span><Check />No money changes hands.</span><span><Check />Always on your terms.</span></div></div></div></section>
      <section className="launch-section launch-privacy"><div><span className="eyebrow">TRUST, WITHOUT THE FINE PRINT</span><h2>Your career is personal.<br />Your connections should be too.</h2></div><div><p>Referrer names are shared only after they accept your request. Resumes stay private until acceptance. And a referral is an introduction—not a promise of an interview or a job.</p><Link className="text-link" to="/safety">Our approach to help & safety <ArrowUpRight size={16} /></Link></div></section>
      <section className="launch-section launch-faq"><div><span className="eyebrow">A FEW GOOD QUESTIONS</span><h2>Before you<br />take the next step.</h2></div><div className="launch-faq-list">{questions.map(([question, answer], index) => <div className="launch-faq-item" key={question}><Button variant="ghost" aria-expanded={faq === index} aria-controls={`faq-${index}`} onClick={() => setFaq(faq === index ? null : index)}>{question}{faq === index ? <Minus /> : <Plus />}</Button>{faq === index && <p id={`faq-${index}`}>{answer}</p>}</div>)}</div></section>
      <section className="launch-final"><span className="eyebrow">SMALL CONNECTION. BIG NEXT STEP.</span><h2>What’s on the other side?</h2><Button asChild><Link to="/explore">Explore companies <ArrowUpRight /></Link></Button><p>Referrals are free. Always.</p></section>
    </main>
    <footer className="launch-footer"><Link className="wordmark" to="/">SkipWait<span className="brand-dot">.</span></Link><span>A warmer way in. · skipwait.me</span><span className="flex flex-wrap gap-4"><Link to="/help">Help</Link><Link to="/guidelines">Guidelines</Link><Link to="/terms">Terms</Link><Link to="/privacy">Privacy</Link><Link to="/for-companies">For companies <ArrowUpRight size={14} /></Link></span></footer>
  </div>;
}