import { describe, expect, it } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs";import { tmpdir } from "node:os";import { join } from "node:path";import { spawnSync } from "node:child_process";
const script=join(process.cwd(),"scripts/classify-api-changes.sh");
function run(paths:string[],extra:string[]=[]){const d=mkdtempSync(join(tmpdir(),"api-class-"));const git=(...a:string[])=>{const r=spawnSync("git",a,{cwd:d,encoding:"utf8"});if(r.status)throw Error(r.stderr);return r.stdout.trim()};git("init","-q");git("config","user.email","x@y");git("config","user.name","x");writeFileSync(join(d,"seed"),"x");git("add",".");git("commit","-qm","seed");const before=git("rev-parse","HEAD");for(const p of paths){mkdirSync(join(d,p.split('/').slice(0,-1).join('/')),{recursive:true});writeFileSync(join(d,p),"x");}git("add",".");git("commit","-qm","change");if(extra.length){for(const p of extra){mkdirSync(join(d,p.split('/').slice(0,-1).join('/')),{recursive:true});writeFileSync(join(d,p),"y");}git("add",".");git("commit","-qm","more");}const head=git("rev-parse","HEAD");return spawnSync("bash",[script],{cwd:d,encoding:"utf8",env:{...process.env,EVENT_NAME:"push",BEFORE_SHA:before,HEAD_SHA:head}}).stdout;}
it("workflow-only validates without deploy",()=>expect(run([".github/workflows/deploy-api.yml"])).toContain("classification=pipeline"));
it("docs and sync logs skip all",()=>expect(run(["docs/SYNC_LOG.md"])).toContain("classification=skip"));
it("server changes deploy",()=>expect(run(["server/x.ts"])).toContain("classification=runtime"));
it.each(["Dockerfile",".dockerignore","pnpm-lock.yaml","patches/x.patch"])("%s deploys",p=>expect(run([p])).toContain("classification=runtime"));
it("mixed changes deploy",()=>expect(run([".github/workflows/deploy-api.yml","server/x.ts"])).toContain("classification=runtime"));
it("multi-commit pushes diff the full before..head range",()=>expect(run(["server/x.ts"],["docs/x.md"])).toContain("classification=runtime"));
