/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminReviewRouteImport } from './routes/admin-review'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AppStatesRouteImport } from './routes/app-states'
import { Route as ApproveRouteImport } from './routes/approve'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AssistantsRouteImport } from './routes/assistants'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ConnectAssistantRouteImport } from './routes/connect-assistant'
import { Route as DeveloperConsoleRouteImport } from './routes/developer-console'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForCompaniesRouteImport } from './routes/for-companies'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LandedRouteImport } from './routes/landed'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferrerRouteImport } from './routes/referrer'
import { Route as ReferrerHomeRouteImport } from './routes/referrer-home'
import { Route as ReferrerSetupRouteImport } from './routes/referrer-setup'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SuggestCompanyRouteImport } from './routes/suggest-company'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThreadRouteImport } from './routes/thread'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as PHandleRouteImport } from './routes/p.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin-review',
  path: '/admin-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatesRoute = AppStatesRouteImport.update({
  id: '/app-states',
  path: '/app-states',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveRoute = ApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsRoute = AssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectAssistantRoute = ConnectAssistantRouteImport.update({
  id: '/connect-assistant',
  path: '/connect-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperConsoleRoute = DeveloperConsoleRouteImport.update({
  id: '/developer-console',
  path: '/developer-console',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCompaniesRoute = ForCompaniesRouteImport.update({
  id: '/for-companies',
  path: '/for-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LandedRoute = LandedRouteImport.update({
  id: '/landed',
  path: '/landed',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferrerRoute = ReferrerRouteImport.update({
  id: '/referrer',
  path: '/referrer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferrerHomeRoute = ReferrerHomeRouteImport.update({
  id: '/referrer-home',
  path: '/referrer-home',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferrerSetupRoute = ReferrerSetupRouteImport.update({
  id: '/referrer-setup',
  path: '/referrer-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestCompanyRoute = SuggestCompanyRouteImport.update({
  id: '/suggest-company',
  path: '/suggest-company',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadRoute = ThreadRouteImport.update({
  id: '/thread',
  path: '/thread',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExploreRoute,
} as any)
const PHandleRoute = PHandleRouteImport.update({
  id: '/p/$handle',
  path: '/p/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-review': typeof AdminReviewRoute
  '/alerts': typeof AlertsRoute
  '/app-states': typeof AppStatesRoute
  '/approve': typeof ApproveRoute
  '/ask': typeof AskRoute
  '/assistants': typeof AssistantsRoute
  '/billing': typeof BillingRoute
  '/connect-assistant': typeof ConnectAssistantRoute
  '/developer-console': typeof DeveloperConsoleRoute
  '/developers': typeof DevelopersRoute
  '/emails': typeof EmailsRoute
  '/employer': typeof EmployerRoute
  '/explore': typeof ExploreRouteWithChildren
  '/for-companies': typeof ForCompaniesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/landed': typeof LandedRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrer': typeof ReferrerRoute
  '/referrer-home': typeof ReferrerHomeRoute
  '/referrer-setup': typeof ReferrerSetupRoute
  '/report': typeof ReportRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/suggest-company': typeof SuggestCompanyRoute
  '/terms': typeof TermsRoute
  '/thread': typeof ThreadRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/work': typeof WorkRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/p/$handle': typeof PHandleRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-review': typeof AdminReviewRoute
  '/alerts': typeof AlertsRoute
  '/app-states': typeof AppStatesRoute
  '/approve': typeof ApproveRoute
  '/ask': typeof AskRoute
  '/assistants': typeof AssistantsRoute
  '/billing': typeof BillingRoute
  '/connect-assistant': typeof ConnectAssistantRoute
  '/developer-console': typeof DeveloperConsoleRoute
  '/developers': typeof DevelopersRoute
  '/emails': typeof EmailsRoute
  '/employer': typeof EmployerRoute
  '/for-companies': typeof ForCompaniesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/landed': typeof LandedRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrer': typeof ReferrerRoute
  '/referrer-home': typeof ReferrerHomeRoute
  '/referrer-setup': typeof ReferrerSetupRoute
  '/report': typeof ReportRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/suggest-company': typeof SuggestCompanyRoute
  '/terms': typeof TermsRoute
  '/thread': typeof ThreadRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/work': typeof WorkRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/p/$handle': typeof PHandleRoute
  '/explore': typeof ExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-review': typeof AdminReviewRoute
  '/alerts': typeof AlertsRoute
  '/app-states': typeof AppStatesRoute
  '/approve': typeof ApproveRoute
  '/ask': typeof AskRoute
  '/assistants': typeof AssistantsRoute
  '/billing': typeof BillingRoute
  '/connect-assistant': typeof ConnectAssistantRoute
  '/developer-console': typeof DeveloperConsoleRoute
  '/developers': typeof DevelopersRoute
  '/emails': typeof EmailsRoute
  '/employer': typeof EmployerRoute
  '/explore': typeof ExploreRouteWithChildren
  '/for-companies': typeof ForCompaniesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/landed': typeof LandedRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrer': typeof ReferrerRoute
  '/referrer-home': typeof ReferrerHomeRoute
  '/referrer-setup': typeof ReferrerSetupRoute
  '/report': typeof ReportRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/suggest-company': typeof SuggestCompanyRoute
  '/terms': typeof TermsRoute
  '/thread': typeof ThreadRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/work': typeof WorkRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/p/$handle': typeof PHandleRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-review'
    | '/alerts'
    | '/app-states'
    | '/approve'
    | '/ask'
    | '/assistants'
    | '/billing'
    | '/connect-assistant'
    | '/developer-console'
    | '/developers'
    | '/emails'
    | '/employer'
    | '/explore'
    | '/for-companies'
    | '/forgot-password'
    | '/guidelines'
    | '/help'
    | '/inbox'
    | '/invite'
    | '/landed'
    | '/onboarding'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/referrer'
    | '/referrer-home'
    | '/referrer-setup'
    | '/report'
    | '/requests'
    | '/reset-password'
    | '/safety'
    | '/settings'
    | '/sign-in'
    | '/suggest-company'
    | '/terms'
    | '/thread'
    | '/verify'
    | '/wallet'
    | '/work'
    | '/explore/$slug'
    | '/p/$handle'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-review'
    | '/alerts'
    | '/app-states'
    | '/approve'
    | '/ask'
    | '/assistants'
    | '/billing'
    | '/connect-assistant'
    | '/developer-console'
    | '/developers'
    | '/emails'
    | '/employer'
    | '/for-companies'
    | '/forgot-password'
    | '/guidelines'
    | '/help'
    | '/inbox'
    | '/invite'
    | '/landed'
    | '/onboarding'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/referrer'
    | '/referrer-home'
    | '/referrer-setup'
    | '/report'
    | '/requests'
    | '/reset-password'
    | '/safety'
    | '/settings'
    | '/sign-in'
    | '/suggest-company'
    | '/terms'
    | '/thread'
    | '/verify'
    | '/wallet'
    | '/work'
    | '/explore/$slug'
    | '/p/$handle'
    | '/explore'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-review'
    | '/alerts'
    | '/app-states'
    | '/approve'
    | '/ask'
    | '/assistants'
    | '/billing'
    | '/connect-assistant'
    | '/developer-console'
    | '/developers'
    | '/emails'
    | '/employer'
    | '/explore'
    | '/for-companies'
    | '/forgot-password'
    | '/guidelines'
    | '/help'
    | '/inbox'
    | '/invite'
    | '/landed'
    | '/onboarding'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/referrer'
    | '/referrer-home'
    | '/referrer-setup'
    | '/report'
    | '/requests'
    | '/reset-password'
    | '/safety'
    | '/settings'
    | '/sign-in'
    | '/suggest-company'
    | '/terms'
    | '/thread'
    | '/verify'
    | '/wallet'
    | '/work'
    | '/explore/$slug'
    | '/p/$handle'
    | '/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AlertsRoute: typeof AlertsRoute
  AppStatesRoute: typeof AppStatesRoute
  ApproveRoute: typeof ApproveRoute
  AskRoute: typeof AskRoute
  AssistantsRoute: typeof AssistantsRoute
  BillingRoute: typeof BillingRoute
  ConnectAssistantRoute: typeof ConnectAssistantRoute
  DeveloperConsoleRoute: typeof DeveloperConsoleRoute
  DevelopersRoute: typeof DevelopersRoute
  EmailsRoute: typeof EmailsRoute
  EmployerRoute: typeof EmployerRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  ForCompaniesRoute: typeof ForCompaniesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuidelinesRoute: typeof GuidelinesRoute
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRoute
  InviteRoute: typeof InviteRoute
  LandedRoute: typeof LandedRoute
  OnboardingRoute: typeof OnboardingRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReferrerRoute: typeof ReferrerRoute
  ReferrerHomeRoute: typeof ReferrerHomeRoute
  ReferrerSetupRoute: typeof ReferrerSetupRoute
  ReportRoute: typeof ReportRoute
  RequestsRoute: typeof RequestsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SuggestCompanyRoute: typeof SuggestCompanyRoute
  TermsRoute: typeof TermsRoute
  ThreadRoute: typeof ThreadRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  WorkRoute: typeof WorkRoute
  PHandleRoute: typeof PHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-review': {
      id: '/admin-review'
      path: '/admin-review'
      fullPath: '/admin-review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-states': {
      id: '/app-states'
      path: '/app-states'
      fullPath: '/app-states'
      preLoaderRoute: typeof AppStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve': {
      id: '/approve'
      path: '/approve'
      fullPath: '/approve'
      preLoaderRoute: typeof ApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants': {
      id: '/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-assistant': {
      id: '/connect-assistant'
      path: '/connect-assistant'
      fullPath: '/connect-assistant'
      preLoaderRoute: typeof ConnectAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-console': {
      id: '/developer-console'
      path: '/developer-console'
      fullPath: '/developer-console'
      preLoaderRoute: typeof DeveloperConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-companies': {
      id: '/for-companies'
      path: '/for-companies'
      fullPath: '/for-companies'
      preLoaderRoute: typeof ForCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landed': {
      id: '/landed'
      path: '/landed'
      fullPath: '/landed'
      preLoaderRoute: typeof LandedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrer': {
      id: '/referrer'
      path: '/referrer'
      fullPath: '/referrer'
      preLoaderRoute: typeof ReferrerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrer-home': {
      id: '/referrer-home'
      path: '/referrer-home'
      fullPath: '/referrer-home'
      preLoaderRoute: typeof ReferrerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrer-setup': {
      id: '/referrer-setup'
      path: '/referrer-setup'
      fullPath: '/referrer-setup'
      preLoaderRoute: typeof ReferrerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggest-company': {
      id: '/suggest-company'
      path: '/suggest-company'
      fullPath: '/suggest-company'
      preLoaderRoute: typeof SuggestCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread': {
      id: '/thread'
      path: '/thread'
      fullPath: '/thread'
      preLoaderRoute: typeof ThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/p/$handle': {
      id: '/p/$handle'
      path: '/p/$handle'
      fullPath: '/p/$handle'
      preLoaderRoute: typeof PHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExploreRouteChildren {
  ExploreSlugRoute: typeof ExploreSlugRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreSlugRoute: ExploreSlugRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminReviewRoute: AdminReviewRoute,
  AlertsRoute: AlertsRoute,
  AppStatesRoute: AppStatesRoute,
  ApproveRoute: ApproveRoute,
  AskRoute: AskRoute,
  AssistantsRoute: AssistantsRoute,
  BillingRoute: BillingRoute,
  ConnectAssistantRoute: ConnectAssistantRoute,
  DeveloperConsoleRoute: DeveloperConsoleRoute,
  DevelopersRoute: DevelopersRoute,
  EmailsRoute: EmailsRoute,
  EmployerRoute: EmployerRoute,
  ExploreRoute: ExploreRouteWithChildren,
  ForCompaniesRoute: ForCompaniesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuidelinesRoute: GuidelinesRoute,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRoute,
  InviteRoute: InviteRoute,
  LandedRoute: LandedRoute,
  OnboardingRoute: OnboardingRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReferrerRoute: ReferrerRoute,
  ReferrerHomeRoute: ReferrerHomeRoute,
  ReferrerSetupRoute: ReferrerSetupRoute,
  ReportRoute: ReportRoute,
  RequestsRoute: RequestsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SuggestCompanyRoute: SuggestCompanyRoute,
  TermsRoute: TermsRoute,
  ThreadRoute: ThreadRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  WorkRoute: WorkRoute,
  PHandleRoute: PHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
