import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { AlertTriangle, ArrowRight, Building2, Check, CheckCircle2, CircleDollarSign, Clock3, Eye, Search, ShieldAlert, ShieldCheck, TrendingUp, UsersRound, X } from "lucide-react";
import { AdminShell, type AdminView } from "@/components/admin-shell";
import { Button } from "@/components/ui/button";
import { launchCompanies } from "@/lib/marketplace-data";
import { pageMeta } from "@/lib/page-meta";

export const Route = createFileRoute("/admin")({ head: () => pageMeta("Admin operations preview", "A design preview of SkipWait marketplace operations, safety, company review, and sustainable growth tools."), component: Admin });

function Admin() {
  const [view, setView] = useState<AdminView>("overview");
  return <AdminShell view={view} onView={setView}><main className="admin-content">{view === "overview" && <Overview onView={setView} />}{view === "companies" && <Companies />}{view === "verifications" && <Verifications />}{view === "reports" && <Reports />}{view === "users" && <Users />}</main></AdminShell>;
}

function Heading({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <div className="admin-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{body}</p></div>; }

function Overview({ onView }: { onView: (view: AdminView) => void }) { return <><Heading eyebrow="MARKETPLACE CONTROL ROOM" title="Operate for trust, not vanity." body="Prioritize safety, healthy supply, and useful introductions. Never optimize for referral volume alone."/><section className="admin-kpi-grid"><div><ShieldCheck /><span>Verification queue</span><strong>—</strong><small>Live data not connected</small></div><div><ShieldAlert /><span>Open reports</span><strong>—</strong><small>Live data not connected</small></div><div><Building2 /><span>Company coverage</span><strong>5</strong><small>Confirmed launch companies</small></div><div><UsersRound /><span>Marketplace users</span><strong>—</strong><small>No fabricated count</small></div></section><section className="admin-grid"><div className="admin-panel"><header><div><span className="eyebrow">OPERATIONS</span><h2>Priority queues</h2></div><span className="preview-label">NO LIVE DATA</span></header>{[["Review company submissions", "Validate domains and prevent duplicates", "companies"], ["Review work-email exceptions", "Resolve only with sufficient evidence", "verifications"], ["Handle safety reports", "Urgent harm and payment requests first", "reports"]].map(([title, body, target]) => <Button key={title} variant="ghost" className="admin-task" onClick={() => onView(target as AdminView)}><span><strong>{title}</strong><small>{body}</small></span><ArrowRight /></Button>)}</div><div className="admin-panel monetization-panel"><span className="eyebrow">SUSTAINABLE, NOT PAY-TO-WIN</span><h2>Monetization guardrails</h2><div><CircleDollarSign /><span><strong>Employer subscriptions</strong><small>Hiring-team workflow and aggregate insights.</small></span></div><div><Eye /><span><strong>Promoted employer profiles</strong><small>Clearly labeled, never prioritized in referral matching.</small></span></div><div><CheckCircle2 /><span><strong>Referrals remain free</strong><small>No commissions or paid queue position.</small></span></div></div></section><section className="sample-chart"><header><div><span className="eyebrow">SAMPLE REPORTING STRUCTURE</span><h2>Healthy growth balances both sides.</h2></div><span className="preview-label">ILLUSTRATIVE · NOT LIVE</span></header><div className="chart-columns" aria-label="Illustrative marketplace chart">{["chart-h-1","chart-h-2","chart-h-3","chart-h-4","chart-h-5","chart-h-6"].map((height,index) => <div key={height}><span className={height} /><small>W{index + 1}</small></div>)}</div><div className="chart-legend"><span><i />Qualified seeker demand</span><span><i />Available referral supply</span></div></section></>; }

function Companies() { return <><Heading eyebrow="COMPANY OPERATIONS" title="Launch directory." body="Five confirmed companies are visible. New submissions require domain and duplicate review."/><div className="admin-toolbar"><label><Search /><input aria-label="Search companies" placeholder="Search company or domain" /></label><Button>Add company</Button></div><section className="admin-table" aria-label="Companies"><header><span>Company</span><span>Coverage</span><span>Status</span><span>Action</span></header>{launchCompanies.map(company => <div key={company.slug}><span className="table-primary"><i className="company-mark">{company.initials}</i><span><strong>{company.name}</strong><small>{company.industry}</small></span></span><span>{company.location}</span><span className="status-pill"><Check />Open door</span><Button variant="ghost">Review <ArrowRight /></Button></div>)}</section></>; }

function Verifications() { return <><Heading eyebrow="TRUST OPERATIONS" title="Verification review." body="Work-email checks confirm address ownership only. Exceptions require a documented decision."/><section className="admin-empty"><span><ShieldCheck /></span><h2>No live verification queue.</h2><p>This preview intentionally shows no invented users. When requests exist, reviewers will see company, domain match, evidence, and decision history.</p><div className="verification-example"><span className="preview-label">EXAMPLE REVIEW STRUCTURE</span><div><span className="company-mark">?</span><span><strong>Identity withheld in preview</strong><small>Company claim · Domain check · Submitted time</small></span></div><footer><Button variant="outline"><X />Request more information</Button><Button><Check />Approve</Button></footer></div></section></>; }

function Reports() { return <><Heading eyebrow="SAFETY OPERATIONS" title="Reports and escalations." body="Payment requests, harassment, identity concerns, and spam should be triaged with context and an audit trail."/><Button asChild className="mb-4"><Link to="/admin-review">Open review queue preview</Link></Button><section className="admin-empty report-empty"><span><CheckCircle2 /></span><h2>No live reports in this preview.</h2><p>Absence here is not a safety claim. The connected product should prioritize urgent reports and preserve evidence.</p></section><section className="severity-guide"><h2>Triage guide</h2><div><span className="severity urgent"><AlertTriangle />Urgent</span><p>Threats, financial solicitation, or exposed sensitive data.</p></div><div><span className="severity review"><Clock3 />Review</span><p>Harassment, impersonation, repeated spam, or policy disputes.</p></div><div><span className="severity normal"><Eye />Routine</span><p>Quality concerns, company corrections, and support requests.</p></div></section></>; }

function Users() { return <><Heading eyebrow="ACCOUNT OPERATIONS" title="User lookup." body="Support legitimate access while keeping restrictions, evidence, and appeals visible to reviewers."/><div className="admin-toolbar"><label><Search /><input aria-label="Search users" placeholder="Search by email or user ID" /></label><Button>Search</Button></div><section className="admin-empty"><span><UsersRound /></span><h2>Search to review an account.</h2><p>No user records are shown in this design preview. Account views should separate profile details, roles, verification, reports, restrictions, and audit history.</p></section></>; }