import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowLeft, Check, Copy, Mail, Share2, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { pageMeta } from "@/lib/page-meta";
import { launchCompanies } from "@/lib/marketplace-data";

export const Route = createFileRoute("/invite")({ head: () => pageMeta("Bring a company to SkipWait", "Request a company or invite someone inside to open a new referral door."), component: Invite });
function Invite() {
  const [mode, setMode] = useState<"request" | "invite">("request");
  const [done, setDone] = useState(false);
  return <main className="page-content invite-page"><Link className="back-link" to="/explore"><ArrowLeft />Back to explore</Link><div className="page-heading"><div><span className="eyebrow">GROW ONE USEFUL DOOR AT A TIME</span><h1>Who should join<br />SkipWait next<span className="brand-dot">?</span></h1><p>Signal seeker demand or invite someone who can genuinely help.</p></div></div><div className="intent-switch invite-switch"><Button variant="ghost" className={mode === "request" ? "selected" : ""} onClick={() => { setMode("request"); setDone(false); }}><UsersRound />Request a company</Button><Button variant="ghost" className={mode === "invite" ? "selected" : ""} onClick={() => { setMode("invite"); setDone(false); }}><Share2 />Invite someone inside</Button></div><section className="invite-panel">{done ? <div className="request-complete"><span className="preview-check"><Check /></span><h2>That’s the growth loop.</h2><p>The live product would capture this signal without posting publicly or sending spam. Nothing happened in this preview.</p><Button onClick={() => setDone(false)}>Try the other path</Button></div> : mode === "request" ? <><span className="eyebrow">SEEKER DEMAND</span><h2>Tell us where you want to work.</h2><p>Your interest helps prioritize where to welcome verified referrers next. It does not create a referral request.</p><label>Company name<input placeholder="Search or enter a company" list="launch-companies" /><datalist id="launch-companies">{launchCompanies.map(company => <option key={company.slug} value={company.name} />)}</datalist></label><label>Work function<select><option>Choose a function</option><option>Engineering</option><option>Product</option><option>Design</option><option>Data</option><option>Operations</option></select></label><Button onClick={() => setDone(true)}>Preview company request</Button></> : <><span className="eyebrow">REFERRER NETWORK</span><h2>Invite a trusted colleague.</h2><p>Share a neutral invitation. They choose whether to verify and open their door—no pressure, no referral obligation.</p><div className="share-link"><span>skipwait.me/referrer</span><Button variant="ghost" size="icon" aria-label="Copy invitation link" onClick={() => setDone(true)}><Copy /></Button></div><Button onClick={() => setDone(true)}><Mail />Preview email invite</Button></>}</section><p className="design-note">DESIGN PREVIEW · NO REQUESTS OR INVITATIONS ARE SENT</p></main>;
}