import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, Bell, Check, FileText, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { pageMeta } from "@/lib/page-meta";

export const Route = createFileRoute("/profile")({ head: () => pageMeta("Profile and privacy preview", "Preview how seekers and referrers control identity, documents, notifications, and availability on SkipWait."), component: Profile });
function Profile() {
  const [role, setRole] = useState<"seeker"|"referrer">("seeker");
  const [saved, setSaved] = useState(false);
  return <main className="page-content profile-page"><div className="page-heading"><div><span className="eyebrow">YOU CONTROL WHAT OPENS</span><h1>Profile & privacy<span className="brand-dot">.</span></h1><p>Share the minimum needed for a useful introduction.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" asChild><Link to="/p/$handle" params={{ handle: "preview" }}>View public profile <ArrowRight /></Link></Button><Button variant="outline" asChild><Link to="/verify">Verify work email</Link></Button><Button variant="outline" asChild><Link to="/onboarding">Setup guide</Link></Button><Button variant="outline" asChild><Link to="/settings">Settings</Link></Button></div></div><div className="intent-switch profile-switch"><Button variant="ghost" className={role === "seeker" ? "selected" : ""} onClick={() => setRole("seeker")}><UserRound />Seeker profile</Button><Button variant="ghost" className={role === "referrer" ? "selected" : ""} onClick={() => setRole("referrer")}><ShieldCheck />Referrer profile</Button></div><section className="profile-layout"><div className="profile-form"><label>Display name<input defaultValue="Your name" /></label><label>Headline<input defaultValue={role === "seeker" ? "Your role and strongest area" : "Your function at work"} /></label>{role === "seeker" ? <label className="upload-field"><FileText /><span><strong>Resume</strong><small>Shared only after you choose and a request is accepted.</small></span><Button variant="outline">Choose file</Button></label> : <label>Company<select><option>Select verified company</option><option>SkipWait</option><option>Wipro</option><option>Go Neutrinos</option><option>TCS</option><option>Merkle</option></select></label>}<Button onClick={() => setSaved(true)}>{saved ? <><Check />Preview saved</> : <>Save preview <ArrowRight /></>}</Button></div><aside className="privacy-controls"><span className="eyebrow">PRIVACY CONTROLS</span><div><LockKeyhole /><span><strong>Not publicly discoverable</strong><small>{role === "seeker" ? "Only referrers reviewing your ask see context." : "Seekers see your company and function, not your name."}</small></span></div><div><Bell /><span><strong>Useful notifications only</strong><small>Requests, decisions, replies, and time-sensitive safety updates.</small></span></div><div><ShieldCheck /><span><strong>Block and report available</strong><small>Leave a conversation without losing access to support.</small></span></div><Link to="/safety">Review safety boundaries <ArrowRight /></Link></aside></section><p className="design-note">PREVIEW ONLY · NOTHING IS UPLOADED OR SAVED</p></main>;
}