import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, BriefcaseBusiness, Check, ChevronDown, Clock3, EyeOff, HeartHandshake, MailCheck, Pause, Settings2, ShieldCheck, UserRound, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { pageMeta } from "@/lib/page-meta";
import { launchCompanies } from "@/lib/marketplace-data";
import { StatusPill } from "@/components/status-pill";

export const Route = createFileRoute("/referrer")({ head: () => pageMeta("Referrer workspace", "Open a door on your terms with private request review, capacity controls, and a clear referral workflow."), component: Referrer });

const views = ["Overview", "Request queue", "Setup & capacity", "Impact"] as const;

function Referrer() {
  const [view, setView] = useState<(typeof views)[number]>("Overview");
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState(0);
  const [capacity, setCapacity] = useState(3);
  const [paused, setPaused] = useState(false);
  return <main className="page-content referrer-workspace">
    <div className="page-heading"><div><span className="eyebrow">REFERRER WORKSPACE</span><h1>Open doors.<br />On your terms<span className="brand-dot">.</span></h1><p>Choose the requests you believe in. Keep your identity private until you accept.</p></div><Button onClick={() => { setOpen(true); setStep(0); }}>Set up as a referrer <ArrowRight /></Button></div>
    <div className="directory-tabs section-tabs" role="tablist" aria-label="Referrer workspace views">{views.map(item => <Button key={item} variant="ghost" role="tab" aria-selected={view === item} className={view === item ? "selected" : ""} onClick={() => setView(item)}>{item}</Button>)}</div>
    {view === "Overview" && <section className="referrer-dashboard"><div className="referrer-callout"><span className="callout-icon"><HeartHandshake /></span><span className="eyebrow">A SMALL ACTION. A BIG NEXT STEP.</span><h2>Help when the fit feels right.</h2><p>You decide your pace, your criteria, and every introduction. Passing is private and always okay.</p><Button onClick={() => setView("Request queue")}>Preview incoming asks <ArrowRight /></Button></div><div className="referrer-control-list"><div><ShieldCheck /><span><strong>Your identity stays private</strong><small>Revealed only after you accept.</small></span></div><div><Settings2 /><span><strong>Set a real capacity</strong><small>Pause or change it at any time.</small></span></div><div><EyeOff /><span><strong>No public ratings</strong><small>Kindness is not a performance metric.</small></span></div></div></section>}
    {view === "Request queue" && <section className="queue-layout"><div className="example-banner"><ShieldCheck />EXAMPLE REQUEST · NOT LIVE ACTIVITY</div><article className="queue-card"><header><span className="company-mark">W</span><div><span className="eyebrow">PRODUCT · WIPRO</span><h2>Product Designer</h2></div><StatusPill status="Requested" /></header><div className="identity-locked"><EyeOff /><span><strong>Identity hidden</strong><small>Shared after you accept the request</small></span></div><div className="request-quality"><span><Check />Official job link included</span><span><Check />Relevant fit note included</span><span><Check />Resume ready after acceptance</span></div><blockquote>“I’ve led two end-to-end redesigns for enterprise workflow products and would value an honest fit check for this role.”</blockquote><footer><Button variant="ghost" asChild><Link to="/thread">Pass privately</Link></Button><Button asChild><Link to="/thread">Open request <ArrowRight /></Link></Button></footer></article><aside className="queue-guidance"><span className="eyebrow">YOUR DECISION</span><h3>A referral is your professional judgment.</h3><p>Review the role and context. Accept only if you’re comfortable making the introduction through your company’s process.</p><Link to="/safety">Safety and boundaries <ArrowRight /></Link></aside></section>}
    {view === "Setup & capacity" && <section className="settings-layout"><div><span className="eyebrow">AVAILABILITY</span><h2>Protect your time.</h2><p>These presentation controls show how referrers can set clear boundaries before requests arrive.</p></div><div className="settings-panel"><label>Company<select><option>Select your company</option>{launchCompanies.map(company => <option key={company.slug}>{company.name}</option>)}</select></label><label>Work function<select><option>Choose a function</option><option>Engineering</option><option>Product</option><option>Design</option><option>Data</option><option>Operations</option></select></label><label className="capacity-control"><span>Monthly request capacity <strong>{capacity}</strong></span><input type="range" min="1" max="10" value={capacity} onChange={event => setCapacity(Number(event.target.value))} /></label><Button className="pause-control" type="button" variant="ghost" aria-pressed={paused} onClick={() => setPaused(!paused)}><span><Pause /><span><strong>Pause new requests</strong><small>Existing conversations stay available.</small></span></span><span className={paused ? "switch on" : "switch"}><i /></span></Button><Button onClick={() => setView("Overview")}>Save preview settings <Check /></Button><span className="design-note">PREVIEW ONLY · SETTINGS ARE NOT SAVED</span></div></section>}
    {view === "Impact" && <section className="impact-zero"><span className="impact-door"><HeartHandshake /></span><span className="eyebrow">YOUR IMPACT STARTS AT ZERO</span><h2>No invented scoreboards.</h2><p>When real introductions happen, this space can reflect actions you control: thoughtful replies, introductions made, and people helped. It will never rank generosity.</p><div><span><strong>0</strong> introductions</span><span><strong>0</strong> active conversations</span><span><strong>0</strong> outcomes shared</span></div><Button onClick={() => setView("Request queue")}>See how a request looks <ArrowRight /></Button></section>}
    {open && <div className="modal-backdrop" onClick={() => setOpen(false)}><section className="app-dialog referrer-setup" role="dialog" aria-modal="true" aria-labelledby="setup-title" onClick={event => event.stopPropagation()}><Button variant="ghost" size="icon" className="dialog-close" aria-label="Close setup" onClick={() => setOpen(false)}><X /></Button><span className="eyebrow">REFERRER SETUP · {step + 1} OF 3</span><div className="request-progress">{[0,1,2].map(index => <span key={index} className={index <= step ? "reached" : ""} />)}</div>{step === 0 && <div className="setup-step"><UserRound /><h2 id="setup-title">Your private profile.</h2><p>Your name is not listed publicly. Seekers see only that someone at the company is open to requests.</p><div className="profile-preview"><span className="company-mark">?</span><span><strong>Verified person inside</strong><small>Identity shown after acceptance</small></span></div></div>}{step === 1 && <div className="setup-step"><MailCheck /><h2 id="setup-title">Verify work email.</h2><p>This confirms access to a company email address—not employment or employer endorsement.</p><Button asChild variant="outline"><Link to="/verify">Verify with a one-time code <ArrowRight /></Link></Button></div>}{step === 2 && <div className="setup-step"><BriefcaseBusiness /><h2 id="setup-title">Choose your lane.</h2><p>Pick the kinds of roles you can assess and how many asks you want to receive.</p><label>Function<select><option>Engineering</option><option>Product</option><option>Design</option><option>Data</option><option>Operations</option></select><ChevronDown /></label></div>}<footer>{step > 0 && <Button variant="ghost" onClick={() => setStep(step - 1)}>Back</Button>}<Button onClick={() => step < 2 ? setStep(step + 1) : setOpen(false)}>{step < 2 ? "Continue" : "Finish preview"}{step < 2 ? <ArrowRight /> : <Check />}</Button></footer><p className="design-note">DESIGN PREVIEW · NO EMAIL IS SENT</p></section></div>}
  </main>;
}