import { ArrowUp, Bot, Loader2, Sparkles } from "lucide-react";
import { useState } from "react";
import { Streamdown } from "streamdown";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

type ChatMessage = { role: "assistant" | "user"; content: string };

const starterPrompts = ["Find roles where my experience is unusually relevant", "Help me choose which Referral Request to send first", "Prepare me for a thoughtful conversation with a Referrer"];

export default function CareerCopilot() {
  const { isAuthenticated } = useAuth(); const [draft, setDraft] = useState(""); const [messages, setMessages] = useState<ChatMessage[]>([{ role: "assistant", content: "I’m Bridge Copilot. Tell me what you’re aiming for, what feels uncertain, or what opportunity you’re considering—I’ll help you decide the next best move." }]);
  const copilot = trpc.ai.copilot.useMutation({ onSuccess: data => setMessages(current => [...current, { role: "assistant", content: data.reply }]) });
  const send = (message = draft) => { const trimmed = message.trim(); if (!trimmed) return; if (!isAuthenticated) { startLogin(); return; } setMessages(current => [...current, { role: "user", content: trimmed }]); setDraft(""); copilot.mutate({ message: trimmed }); };
  return <section className="overflow-hidden rounded-[26px] border border-violet-200 bg-white shadow-[0_24px_70px_rgba(67,53,148,0.13)]"><div className="border-b border-violet-100 bg-[radial-gradient(circle_at_12%_0%,#F0EDFF_0%,#FFFFFF_55%)] px-5 py-5 sm:px-7"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-950 text-violet-200 shadow-lg"><Bot className="h-5 w-5" /></span><div><p className="text-sm font-bold tracking-[-0.02em] text-slate-950">Bridge Copilot</p><p className="mt-0.5 text-xs text-slate-500">Your private career reasoning partner</p></div></div><span className="inline-flex items-center gap-1.5 rounded-full bg-violet-100 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.1em] text-violet-700"><Sparkles className="h-3 w-3" />AI guided</span></div></div><div className="min-h-[280px] space-y-4 px-5 py-5 sm:px-7">{messages.map((message, index) => <div key={index} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm leading-6 ${message.role === "user" ? "rounded-br-sm bg-violet-600 text-white" : "rounded-bl-sm bg-[#F7F6FC] text-slate-700"}`}><Streamdown>{message.content}</Streamdown></div></div>)}{copilot.isPending && <div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin text-violet-600" />Bridge is thinking through the best next move…</div>}</div><div className="border-t border-slate-100 bg-white px-5 py-4 sm:px-7"><div className="flex flex-wrap gap-2">{starterPrompts.map(prompt => <button key={prompt} onClick={() => send(prompt)} className="rounded-full border border-violet-100 bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700 transition hover:border-violet-200 hover:bg-violet-100">{prompt}</button>)}</div><div className="mt-3 flex items-end gap-2 rounded-2xl border border-slate-200 bg-white p-2 focus-within:border-violet-400 focus-within:ring-4 focus-within:ring-violet-100"><textarea value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(); } }} className="min-h-12 flex-1 resize-none bg-transparent px-2 py-2 text-sm leading-5 outline-none placeholder:text-slate-400" placeholder={isAuthenticated ? "Ask Bridge Copilot anything about your next move…" : "Sign in to ask Bridge Copilot…"} /><button disabled={copilot.isPending || !draft.trim()} onClick={() => send()} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-950 text-white transition hover:bg-violet-700 disabled:opacity-35"><ArrowUp className="h-4 w-4" /></button></div><p className="mt-2 text-[10px] text-slate-400">Copilot offers guidance, not guarantees. You stay in control of every introduction.</p></div></section>;
}
