import { Bell, BriefcaseBusiness, Compass, LayoutDashboard, MessageCircle, UserRound, UsersRound } from "lucide-react";
import { Link, useLocation } from "wouter";
import { Brand } from "./Brand";
import AvatarMark from "./AvatarMark";
import { useAuth } from "@/_core/hooks/useAuth";

const navItems = [{ label: "Overview", href: "/dashboard", icon: LayoutDashboard }, { label: "Job Listings", href: "/jobs", icon: BriefcaseBusiness }, { label: "Community and Explore", href: "/community", icon: Compass }, { label: "Messages", href: "/messages", icon: MessageCircle }, { label: "Notifications", href: "/notifications", icon: Bell }, { label: "Profile", href: "/profile", icon: UserRound }];

export default function DashboardLayout({ children, title, eyebrow, actions }: { children: React.ReactNode; title: string; eyebrow?: string; actions?: React.ReactNode }) {
  const [location] = useLocation(); const { user } = useAuth(); const role = typeof window !== "undefined" ? localStorage.getItem("bridge-role") || "Job Seeker" : "Job Seeker"; const initial = (user?.name || "Avery Morgan").split(" ").map(part => part[0]).join("").slice(0, 2).toUpperCase();
  return <div className="min-h-screen bg-[#F8F8FC] text-slate-900"><aside className="fixed inset-y-0 left-0 z-20 hidden w-[238px] flex-col border-r border-slate-200 bg-white px-4 py-5 lg:flex"><Brand /><div className="mt-10 px-2"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Your workspace</p><p className="mt-1 text-sm font-semibold text-slate-700">{role}</p></div><nav className="mt-5 space-y-1" aria-label="Workspace navigation">{navItems.map(item => { const active = location === item.href || (item.href === "/jobs" && location.startsWith("/referral")); return <Link key={item.href} href={item.href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-colors ${active ? "bg-violet-50 text-violet-700" : "text-slate-600 hover:bg-slate-50 hover:text-slate-950"}`}><item.icon className="h-4 w-4" />{item.label}</Link>; })}</nav><div className="mt-auto rounded-2xl bg-slate-950 p-4 text-white"><UsersRound className="h-4 w-4 text-violet-300" /><p className="mt-3 text-sm font-semibold">Every introduction counts.</p><p className="mt-1 text-xs leading-5 text-slate-400">Be clear, considerate, and keep the conversation human.</p></div></aside><div className="lg:pl-[238px]"><header className="sticky top-0 z-10 border-b border-slate-200/80 bg-[#F8F8FC]/90 px-5 py-4 backdrop-blur lg:px-10"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-4"><div><p className="text-xs font-semibold text-violet-600">{eyebrow || role}</p><h1 className="mt-0.5 text-xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-2xl">{title}</h1></div><div className="flex items-center gap-3">{actions}<Link href="/profile" className="hidden items-center gap-2 rounded-full border border-slate-200 bg-white py-1.5 pl-1.5 pr-3 text-xs font-semibold text-slate-700 shadow-sm sm:flex"><AvatarMark initials={initial} size="sm" /><span>{user?.name || "Avery Morgan"}</span></Link></div></div></header><main className="mx-auto max-w-[1440px] px-5 py-7 lg:px-10 lg:py-9">{children}</main></div><nav className="fixed inset-x-0 bottom-0 z-30 flex border-t border-slate-200 bg-white/95 px-2 py-2 backdrop-blur lg:hidden">{navItems.slice(0, 5).map(item => <Link key={item.href} href={item.href} className={`flex min-w-0 flex-1 flex-col items-center gap-1 rounded-lg px-1 py-1.5 text-[9px] font-semibold ${location === item.href ? "text-violet-700" : "text-slate-500"}`}><item.icon className="h-4 w-4" /><span className="truncate">{item.label.split(" ")[0]}</span></Link>)}</nav></div>;
}
