const STOPPED_CONTAINER_PROXY_ERROR = "Error proxying request to container: The container is not running, consider calling start()";

export type ContainerRecoveryStub = {
  fetch(request: Request): Promise<Response>;
  start(
    startOptions?: { envVars?: Record<string, string>; entrypoint?: string[]; enableInternet?: boolean },
    waitOptions?: { portToCheck: number; signal?: AbortSignal; retries?: number; waitInterval?: number }
  ): Promise<void>;
};

export async function fetchContainerWithStoppedRecovery(
  container: ContainerRecoveryStub,
  request: Request
): Promise<Response> {
  // Preserve a replayable body before the first RPC. The stopped-container error
  // is generated by Cloudflare before the request reaches Express.
  const retryRequest = request.clone();
  const first = await container.fetch(request);
  if (first.status !== 500) return first;
  const diagnostic = await first.clone().text();
  if (diagnostic.trim() !== STOPPED_CONTAINER_PROXY_ERROR) return first;

  // The library normally starts on fetch. Recover only from Cloudflare's exact
  // stopped-instance diagnostic, start once, then retry the original request once.
  await container.start(undefined, {
    portToCheck: 3000,
    signal: retryRequest.signal,
    retries: 8,
    waitInterval: 500,
  });
  return container.fetch(retryRequest);
}
